//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public Plant()
        {
            this.Comment = new HashSet<Comment>();
            this.DownTime = new HashSet<DownTime>();
            this.DownTimeEquipment = new HashSet<DownTimeEquipment>();
            this.DownTimeReason = new HashSet<DownTimeReason>();
            this.EndOfRun = new HashSet<EndOfRun>();
            this.EndOfRunRework = new HashSet<EndOfRunRework>();
            this.EndOfRunTPOFeeder = new HashSet<EndOfRunTPOFeeder>();
            this.IMLineScrap = new HashSet<IMLineScrap>();
            this.IMProduction = new HashSet<IMProduction>();
            this.IMQC = new HashSet<IMQC>();
            this.ProductionBudget = new HashSet<ProductionBudget>();
            this.ProductionLineSchedule = new HashSet<ProductionLineSchedule>();
            this.ProductionShift = new HashSet<ProductionShift>();
            this.ProductionShiftUse = new HashSet<ProductionShiftUse>();
            this.QCKickout = new HashSet<QCKickout>();
            this.QCPrintSpecification = new HashSet<QCPrintSpecification>();
            this.QCRedHold = new HashSet<QCRedHold>();
            this.RawMaterialAction = new HashSet<RawMaterialAction>();
            this.RawMaterialQC = new HashSet<RawMaterialQC>();
            this.RawMaterialReceived = new HashSet<RawMaterialReceived>();
            this.RawMaterialReceivedSizeLimit = new HashSet<RawMaterialReceivedSizeLimit>();
            this.RawMaterialTest = new HashSet<RawMaterialTest>();
            this.ScrimAction = new HashSet<ScrimAction>();
            this.ScrimActionType = new HashSet<ScrimActionType>();
            this.ScrimRoll = new HashSet<ScrimRoll>();
            this.ScrimType = new HashSet<ScrimType>();
            this.TPOBatch = new HashSet<TPOBatch>();
            this.TPOCProductRoll = new HashSet<TPOCProductRoll>();
            this.TPOFormulationLineProduct = new HashSet<TPOFormulationLineProduct>();
            this.TPOLineScrap = new HashSet<TPOLineScrap>();
            this.TPOLineScrapCode = new HashSet<TPOLineScrapCode>();
            this.TPOQC = new HashSet<TPOQC>();
            this.TPORawMaterialFormulation = new HashSet<TPORawMaterialFormulation>();
            this.TPOReclaimAction = new HashSet<TPOReclaimAction>();
            this.TPOReclaimWIP = new HashSet<TPOReclaimWIP>();
            this.TPOReworkAction = new HashSet<TPOReworkAction>();
            this.TPOReworkRoll = new HashSet<TPOReworkRoll>();
            this.TPOSpecificGravity = new HashSet<TPOSpecificGravity>();
            this.UnitOfMeasureDefault = new HashSet<UnitOfMeasureDefault>();
            this.User = new HashSet<User>();
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<DownTime> DownTime { get; set; }
        public virtual ICollection<DownTimeEquipment> DownTimeEquipment { get; set; }
        public virtual ICollection<DownTimeReason> DownTimeReason { get; set; }
        public virtual ICollection<EndOfRun> EndOfRun { get; set; }
        public virtual ICollection<EndOfRunRework> EndOfRunRework { get; set; }
        public virtual ICollection<EndOfRunTPOFeeder> EndOfRunTPOFeeder { get; set; }
        public virtual ICollection<IMLineScrap> IMLineScrap { get; set; }
        public virtual ICollection<IMProduction> IMProduction { get; set; }
        public virtual ICollection<IMQC> IMQC { get; set; }
        public virtual ICollection<ProductionBudget> ProductionBudget { get; set; }
        public virtual ICollection<ProductionLineSchedule> ProductionLineSchedule { get; set; }
        public virtual ICollection<ProductionShift> ProductionShift { get; set; }
        public virtual ICollection<ProductionShiftUse> ProductionShiftUse { get; set; }
        public virtual ICollection<QCKickout> QCKickout { get; set; }
        public virtual ICollection<QCPrintSpecification> QCPrintSpecification { get; set; }
        public virtual ICollection<QCRedHold> QCRedHold { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialAction { get; set; }
        public virtual ICollection<RawMaterialQC> RawMaterialQC { get; set; }
        public virtual ICollection<RawMaterialReceived> RawMaterialReceived { get; set; }
        public virtual ICollection<RawMaterialReceivedSizeLimit> RawMaterialReceivedSizeLimit { get; set; }
        public virtual ICollection<RawMaterialTest> RawMaterialTest { get; set; }
        public virtual ICollection<ScrimAction> ScrimAction { get; set; }
        public virtual ICollection<ScrimActionType> ScrimActionType { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRoll { get; set; }
        public virtual ICollection<ScrimType> ScrimType { get; set; }
        public virtual ICollection<TPOBatch> TPOBatch { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRoll { get; set; }
        public virtual ICollection<TPOFormulationLineProduct> TPOFormulationLineProduct { get; set; }
        public virtual ICollection<TPOLineScrap> TPOLineScrap { get; set; }
        public virtual ICollection<TPOLineScrapCode> TPOLineScrapCode { get; set; }
        public virtual ICollection<TPOQC> TPOQC { get; set; }
        public virtual ICollection<TPORawMaterialFormulation> TPORawMaterialFormulation { get; set; }
        public virtual ICollection<TPOReclaimAction> TPOReclaimAction { get; set; }
        public virtual ICollection<TPOReclaimWIP> TPOReclaimWIP { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkAction { get; set; }
        public virtual ICollection<TPOReworkRoll> TPOReworkRoll { get; set; }
        public virtual ICollection<TPOSpecificGravity> TPOSpecificGravity { get; set; }
        public virtual ICollection<UnitOfMeasureDefault> UnitOfMeasureDefault { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}
