//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialReceived
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int RawMaterialID { get; set; }
        public Nullable<int> LotID { get; set; }
        public Nullable<int> SizeTypeID { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string ReceivedBy { get; set; }
        public string CoA { get; set; }
        public double QuantityShipped { get; set; }
        public double QuantityReceived { get; set; }
        public int QuantityUoMID { get; set; }
        public double QuantityUsedThisLot { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
