//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialQC
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public Nullable<int> QCTechUserID { get; set; }
        public int RawMaterialID { get; set; }
        public string RawMaterialLotID { get; set; }
        public Nullable<bool> VisualInspection { get; set; }
        public Nullable<double> SpecGrav { get; set; }
        public Nullable<double> ColorCoA { get; set; }
        public Nullable<double> ColorFS { get; set; }
        public Nullable<double> MFCoA { get; set; }
        public Nullable<double> MFFS { get; set; }
        public Nullable<double> ACCoA { get; set; }
        public Nullable<double> ACFS { get; set; }
        public Nullable<double> MoistCoA { get; set; }
        public Nullable<double> MoistFS { get; set; }
        public Nullable<double> CBCoA { get; set; }
        public Nullable<double> CBFS { get; set; }
        public string BoxCarTested { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual User User { get; set; }
    }
}
