//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAssignment
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int RoleId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Role Role { get; set; }
    }
}
