//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.SecuredArea = new HashSet<SecuredArea>();
            this.RoleAssignment = new HashSet<RoleAssignment>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<SecuredArea> SecuredArea { get; set; }
        public virtual ICollection<RoleAssignment> RoleAssignment { get; set; }
    }
}
