//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrimType
    {
        public ScrimType()
        {
            this.ScrimRoll = new HashSet<ScrimRoll>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int WidthUoMID { get; set; }
        public int WeightUoMID { get; set; }
        public int LengthUoMID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
        public double Weight { get; set; }
        public bool IsLiner { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRoll { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure2 { get; set; }
    }
}
