//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuredArea
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public string Form { get; set; }
        public string Section { get; set; }
        public bool WriteAccess { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
