//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestLimitType
    {
        public TestLimitType()
        {
            this.RawMaterialTest = new HashSet<RawMaterialTest>();
            this.RawMaterialTest1 = new HashSet<RawMaterialTest>();
            this.RawMaterialTest2 = new HashSet<RawMaterialTest>();
            this.RawMaterialTest3 = new HashSet<RawMaterialTest>();
            this.RawMaterialTest4 = new HashSet<RawMaterialTest>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<RawMaterialTest> RawMaterialTest { get; set; }
        public virtual ICollection<RawMaterialTest> RawMaterialTest1 { get; set; }
        public virtual ICollection<RawMaterialTest> RawMaterialTest2 { get; set; }
        public virtual ICollection<RawMaterialTest> RawMaterialTest3 { get; set; }
        public virtual ICollection<RawMaterialTest> RawMaterialTest4 { get; set; }
    }
}
