//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOCProductRoll
    {
        public TPOCProductRoll()
        {
            this.QCKickout = new HashSet<QCKickout>();
            this.QCRedHold = new HashSet<QCRedHold>();
            this.ScrimAction = new HashSet<ScrimAction>();
            this.TPOCProductRoll1 = new HashSet<TPOCProductRoll>();
            this.TPOQC = new HashSet<TPOQC>();
            this.TPOReworkAction = new HashSet<TPOReworkAction>();
            this.TPOSpecificGravity = new HashSet<TPOSpecificGravity>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int LineID { get; set; }
        public int ProductID { get; set; }
        public int WorkOrderID { get; set; }
        public int ShiftID { get; set; }
        public Nullable<int> MasterRollID { get; set; }
        public int LengthUoMID { get; set; }
        public int WeightUoMID { get; set; }
        public string Code { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public double Length { get; set; }
        public double Weight { get; set; }
        public int BatchNumber { get; set; }
        public string Comments { get; set; }
        public bool Modified { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual ICollection<QCKickout> QCKickout { get; set; }
        public virtual ICollection<QCRedHold> QCRedHold { get; set; }
        public virtual ICollection<ScrimAction> ScrimAction { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRoll1 { get; set; }
        public virtual TPOCProductRoll TPOCProductRoll2 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<TPOQC> TPOQC { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkAction { get; set; }
        public virtual ICollection<TPOSpecificGravity> TPOSpecificGravity { get; set; }
    }
}
