//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOLineScrap
    {
        public TPOLineScrap()
        {
            this.TPOReclaimAction = new HashSet<TPOReclaimAction>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int ShiftID { get; set; }
        public int WorkOrderID { get; set; }
        public Nullable<int> ReworkRollID { get; set; }
        public int TypeID { get; set; }
        public string Code { get; set; }
        public string ScrapCode { get; set; }
        public int BatchNumber { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Weight { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual TPOLineScrapType TPOLineScrapType { get; set; }
        public virtual TPOReworkRoll TPOReworkRoll { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<TPOReclaimAction> TPOReclaimAction { get; set; }
    }
}
