//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOQCDimensionalStabilityDetail
    {
        public int TPOQCID { get; set; }
        public Nullable<double> Machine100 { get; set; }
        public Nullable<double> Machine80 { get; set; }
        public Nullable<double> Transverse100 { get; set; }
        public Nullable<double> Transverse80 { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual TPOQC TPOQC { get; set; }
    }
}
