//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOQC
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int RollID { get; set; }
        public int LineID { get; set; }
        public int LotID { get; set; }
        public int ShiftID { get; set; }
        public int LabTechUserID { get; set; }
        public int ProductID { get; set; }
        public int TypeID { get; set; }
        public int WidthUoMID { get; set; }
        public Nullable<double> EastWidth { get; set; }
        public Nullable<double> WestWidth { get; set; }
        public Nullable<double> MassArea { get; set; }
        public Nullable<bool> PrintPass { get; set; }
        public Nullable<bool> LotPass { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual TPOCProductRoll TPOCProductRoll { get; set; }
        public virtual TPOQCType TPOQCType { get; set; }
        public virtual User User { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual TPOQC2X2Detail TPOQC2X2Detail { get; set; }
        public virtual TPOQCAshDetail TPOQCAshDetail { get; set; }
        public virtual TPOQCCapThicknessDetail TPOQCCapThicknessDetail { get; set; }
        public virtual TPOQCColorDetail TPOQCColorDetail { get; set; }
        public virtual TPOQCCoreThicknessDetail TPOQCCoreThicknessDetail { get; set; }
        public virtual TPOQCDimensionalStabilityDetail TPOQCDimensionalStabilityDetail { get; set; }
        public virtual TPOQCFlashElongationDetail TPOQCFlashElongationDetail { get; set; }
        public virtual TPOQCFlashTearingDetail TPOQCFlashTearingDetail { get; set; }
        public virtual TPOQCFlashTensileDetail TPOQCFlashTensileDetail { get; set; }
        public virtual TPOQCGrabElongationDetail TPOQCGrabElongationDetail { get; set; }
        public virtual TPOQCGrabTearingDetail TPOQCGrabTearingDetail { get; set; }
        public virtual TPOQCGrabTensileDetail TPOQCGrabTensileDetail { get; set; }
        public virtual TPOQCGumDetail TPOQCGumDetail { get; set; }
        public virtual TPOQCOverallThicknessDetail TPOQCOverallThicknessDetail { get; set; }
        public virtual TPOQCPlyDetail TPOQCPlyDetail { get; set; }
        public virtual TPOQCPrintMeasurementDetail TPOQCPrintMeasurementDetail { get; set; }
        public virtual TPOQCPunctureDetail TPOQCPunctureDetail { get; set; }
        public virtual TPOQCSpecificGravityDetail TPOQCSpecificGravityDetail { get; set; }
        public virtual TPOQCThicknessFromEdgeDetail TPOQCThicknessFromEdgeDetail { get; set; }
        public virtual TPOQCWeldStrengthDetail TPOQCWeldStrengthDetail { get; set; }
    }
}
