//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOQCThicknessFromEdgeDetail
    {
        public int TPOQCID { get; set; }
        public Nullable<double> EastThick1 { get; set; }
        public Nullable<double> EastThick2 { get; set; }
        public Nullable<double> EastThick3 { get; set; }
        public Nullable<double> EastThick4 { get; set; }
        public Nullable<double> EastThick5 { get; set; }
        public Nullable<double> EastThick6 { get; set; }
        public Nullable<double> EastThick7 { get; set; }
        public Nullable<double> EastThick8 { get; set; }
        public Nullable<double> EastThick9 { get; set; }
        public Nullable<double> EastThick10 { get; set; }
        public Nullable<double> EastThick11 { get; set; }
        public Nullable<double> EastThick12 { get; set; }
        public Nullable<double> WestThick1 { get; set; }
        public Nullable<double> WestThick2 { get; set; }
        public Nullable<double> WestThick3 { get; set; }
        public Nullable<double> WestThick4 { get; set; }
        public Nullable<double> WestThick5 { get; set; }
        public Nullable<double> WestThick6 { get; set; }
        public Nullable<double> WestThick7 { get; set; }
        public Nullable<double> WestThick8 { get; set; }
        public Nullable<double> WestThick9 { get; set; }
        public Nullable<double> WestThick10 { get; set; }
        public Nullable<double> WestThick11 { get; set; }
        public Nullable<double> WestThick12 { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual TPOQC TPOQC { get; set; }
    }
}
