//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOQCPlyDetail
    {
        public int TPOQCID { get; set; }
        public string Ply1 { get; set; }
        public Nullable<double> Ply2 { get; set; }
        public Nullable<double> Ply3 { get; set; }
        public Nullable<double> Ply4 { get; set; }
        public Nullable<double> Ply5 { get; set; }
        public Nullable<double> Ply6 { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual TPOQC TPOQC { get; set; }
    }
}
