//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOQCPrintMeasurementDetail
    {
        public int TPOQCID { get; set; }
        public Nullable<double> TackLine { get; set; }
        public Nullable<double> LapLine { get; set; }
        public Nullable<double> WeldLine { get; set; }
        public Nullable<double> DateLine { get; set; }
        public Nullable<double> WeldToLapLine { get; set; }
        public Nullable<double> Center { get; set; }
        public Nullable<double> TackLineA { get; set; }
        public Nullable<double> LapLineA { get; set; }
        public Nullable<double> WeldLineA { get; set; }
        public Nullable<double> DateLineA { get; set; }
        public Nullable<double> TackLineB { get; set; }
        public Nullable<double> LapLineB { get; set; }
        public Nullable<double> WeldLineB { get; set; }
        public Nullable<double> DateLineB { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual TPOQC TPOQC { get; set; }
    }
}
