//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOReworkAction
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int LineID { get; set; }
        public int ShiftID { get; set; }
        public int StartRollID { get; set; }
        public int StartRoll2ID { get; set; }
        public int OutputRollID { get; set; }
        public int NewProductID { get; set; }
        public int TypeID { get; set; }
        public int WidthUoMID { get; set; }
        public int LengthUoMID { get; set; }
        public int WeightUoMID { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
        public double Weight { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual TPOCProductRoll TPOCProductRoll { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual TPOReworkRoll TPOReworkRoll { get; set; }
        public virtual TPOReworkRoll TPOReworkRoll1 { get; set; }
        public virtual TPOReworkActionType TPOReworkActionType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure2 { get; set; }
    }
}
