//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOReclaimAction
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int LineID { get; set; }
        public int ShiftID { get; set; }
        public int TypeID { get; set; }
        public int ReclaimTypeID { get; set; }
        public int TPOLineScrapID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public double ActionAmount { get; set; }
        public double CompAmount { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual ReclaimType ReclaimType { get; set; }
        public virtual TPOLineScrap TPOLineScrap { get; set; }
        public virtual TPOReclaimActionType TPOReclaimActionType { get; set; }
    }
}
