//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOReworkRoll
    {
        public TPOReworkRoll()
        {
            this.TPOLineScrap = new HashSet<TPOLineScrap>();
            this.TPOReworkAction = new HashSet<TPOReworkAction>();
            this.TPOReworkAction1 = new HashSet<TPOReworkAction>();
        }
    
        public int ID { get; set; }
        public int LineID { get; set; }
        public int ShiftID { get; set; }
        public int ProductID { get; set; }
        public int PlantID { get; set; }
        public string Code { get; set; }
        public double Length { get; set; }
        public int LengthUoMID { get; set; }
        public double Weight { get; set; }
        public int WeightUoMID { get; set; }
        public bool Processed { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual ICollection<TPOLineScrap> TPOLineScrap { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkAction { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkAction1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
    }
}
