//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOSpecificGravity
    {
        public TPOSpecificGravity()
        {
            this.TPOSpecificGravityWeightDetail = new HashSet<TPOSpecificGravityWeightDetail>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int RawMaterialID { get; set; }
        public int RollID { get; set; }
        public Nullable<int> QCTechUserID { get; set; }
        public double DenIso { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual TPOCProductRoll TPOCProductRoll { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TPOSpecificGravityWeightDetail> TPOSpecificGravityWeightDetail { get; set; }
    }
}
