//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public UnitOfMeasure()
        {
            this.IMLineScrap = new HashSet<IMLineScrap>();
            this.IMProduction = new HashSet<IMProduction>();
            this.RawMaterialReceived = new HashSet<RawMaterialReceived>();
            this.ScrimRoll = new HashSet<ScrimRoll>();
            this.ScrimRoll1 = new HashSet<ScrimRoll>();
            this.ScrimType = new HashSet<ScrimType>();
            this.ScrimType1 = new HashSet<ScrimType>();
            this.ScrimType2 = new HashSet<ScrimType>();
            this.TPOCProductRoll = new HashSet<TPOCProductRoll>();
            this.TPOCProductRoll1 = new HashSet<TPOCProductRoll>();
            this.TPOQC = new HashSet<TPOQC>();
            this.TPOQC2X2Detail = new HashSet<TPOQC2X2Detail>();
            this.TPOQCCapThicknessDetail = new HashSet<TPOQCCapThicknessDetail>();
            this.TPOQCCoreThicknessDetail = new HashSet<TPOQCCoreThicknessDetail>();
            this.TPOQCFlashElongationDetail = new HashSet<TPOQCFlashElongationDetail>();
            this.TPOQCFlashTearingDetail = new HashSet<TPOQCFlashTearingDetail>();
            this.TPOQCFlashTensileDetail = new HashSet<TPOQCFlashTensileDetail>();
            this.TPOQCGrabElongationDetail = new HashSet<TPOQCGrabElongationDetail>();
            this.TPOQCGrabTearingDetail = new HashSet<TPOQCGrabTearingDetail>();
            this.TPOQCGrabTensileDetail = new HashSet<TPOQCGrabTensileDetail>();
            this.TPOQCOverallThicknessDetail = new HashSet<TPOQCOverallThicknessDetail>();
            this.TPOReworkAction = new HashSet<TPOReworkAction>();
            this.TPOReworkAction1 = new HashSet<TPOReworkAction>();
            this.TPOReworkAction2 = new HashSet<TPOReworkAction>();
            this.TPOReworkRoll = new HashSet<TPOReworkRoll>();
            this.TPOReworkRoll1 = new HashSet<TPOReworkRoll>();
            this.UnitOfMeasureConversion = new HashSet<UnitOfMeasureConversion>();
            this.UnitOfMeasureConversion1 = new HashSet<UnitOfMeasureConversion>();
            this.UnitOfMeasureDefault = new HashSet<UnitOfMeasureDefault>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<IMLineScrap> IMLineScrap { get; set; }
        public virtual ICollection<IMProduction> IMProduction { get; set; }
        public virtual ICollection<RawMaterialReceived> RawMaterialReceived { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRoll { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRoll1 { get; set; }
        public virtual ICollection<ScrimType> ScrimType { get; set; }
        public virtual ICollection<ScrimType> ScrimType1 { get; set; }
        public virtual ICollection<ScrimType> ScrimType2 { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRoll { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRoll1 { get; set; }
        public virtual ICollection<TPOQC> TPOQC { get; set; }
        public virtual ICollection<TPOQC2X2Detail> TPOQC2X2Detail { get; set; }
        public virtual ICollection<TPOQCCapThicknessDetail> TPOQCCapThicknessDetail { get; set; }
        public virtual ICollection<TPOQCCoreThicknessDetail> TPOQCCoreThicknessDetail { get; set; }
        public virtual ICollection<TPOQCFlashElongationDetail> TPOQCFlashElongationDetail { get; set; }
        public virtual ICollection<TPOQCFlashTearingDetail> TPOQCFlashTearingDetail { get; set; }
        public virtual ICollection<TPOQCFlashTensileDetail> TPOQCFlashTensileDetail { get; set; }
        public virtual ICollection<TPOQCGrabElongationDetail> TPOQCGrabElongationDetail { get; set; }
        public virtual ICollection<TPOQCGrabTearingDetail> TPOQCGrabTearingDetail { get; set; }
        public virtual ICollection<TPOQCGrabTensileDetail> TPOQCGrabTensileDetail { get; set; }
        public virtual ICollection<TPOQCOverallThicknessDetail> TPOQCOverallThicknessDetail { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkAction { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkAction1 { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkAction2 { get; set; }
        public virtual ICollection<TPOReworkRoll> TPOReworkRoll { get; set; }
        public virtual ICollection<TPOReworkRoll> TPOReworkRoll1 { get; set; }
        public virtual ICollection<UnitOfMeasureConversion> UnitOfMeasureConversion { get; set; }
        public virtual ICollection<UnitOfMeasureConversion> UnitOfMeasureConversion1 { get; set; }
        public virtual UnitOfMeasureType UnitOfMeasureType { get; set; }
        public virtual ICollection<UnitOfMeasureDefault> UnitOfMeasureDefault { get; set; }
    }
}
