//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.IMQC = new HashSet<IMQC>();
            this.IMQC1 = new HashSet<IMQC>();
            this.QCKickout = new HashSet<QCKickout>();
            this.QCKickout1 = new HashSet<QCKickout>();
            this.QCKickout2 = new HashSet<QCKickout>();
            this.QCRedHold = new HashSet<QCRedHold>();
            this.QCRedHold1 = new HashSet<QCRedHold>();
            this.QCRedHold2 = new HashSet<QCRedHold>();
            this.QCRedHold3 = new HashSet<QCRedHold>();
            this.RawMaterialAction = new HashSet<RawMaterialAction>();
            this.RawMaterialQC = new HashSet<RawMaterialQC>();
            this.ScrimAction = new HashSet<ScrimAction>();
            this.SupervisorOnShift = new HashSet<SupervisorOnShift>();
            this.TPOQC = new HashSet<TPOQC>();
            this.TPOSpecificGravity = new HashSet<TPOSpecificGravity>();
            this.RoleAssignment = new HashSet<RoleAssignment>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<IMQC> IMQC { get; set; }
        public virtual ICollection<IMQC> IMQC1 { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ICollection<QCKickout> QCKickout { get; set; }
        public virtual ICollection<QCKickout> QCKickout1 { get; set; }
        public virtual ICollection<QCKickout> QCKickout2 { get; set; }
        public virtual ICollection<QCRedHold> QCRedHold { get; set; }
        public virtual ICollection<QCRedHold> QCRedHold1 { get; set; }
        public virtual ICollection<QCRedHold> QCRedHold2 { get; set; }
        public virtual ICollection<QCRedHold> QCRedHold3 { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialAction { get; set; }
        public virtual ICollection<RawMaterialQC> RawMaterialQC { get; set; }
        public virtual ICollection<ScrimAction> ScrimAction { get; set; }
        public virtual ICollection<SupervisorOnShift> SupervisorOnShift { get; set; }
        public virtual ICollection<TPOQC> TPOQC { get; set; }
        public virtual ICollection<TPOSpecificGravity> TPOSpecificGravity { get; set; }
        public virtual ICollection<RoleAssignment> RoleAssignment { get; set; }
    }
}
