//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO_Reporting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.Comment1 = new HashSet<Comment>();
            this.DownTime = new HashSet<DownTime>();
            this.EndOfRun = new HashSet<EndOfRun>();
            this.EndOfRunTPOFeeder = new HashSet<EndOfRunTPOFeeder>();
            this.IMLineScrap = new HashSet<IMLineScrap>();
            this.IMProduction = new HashSet<IMProduction>();
            this.RawMaterialAction = new HashSet<RawMaterialAction>();
            this.ScrimAction = new HashSet<ScrimAction>();
            this.TPOCProductRoll = new HashSet<TPOCProductRoll>();
            this.TPOLineScrap = new HashSet<TPOLineScrap>();
        }
    
        public int ID { get; set; }
        public int LineID { get; set; }
        public int ProductID { get; set; }
        public int PlantID { get; set; }
        public string Code { get; set; }
        public int RunOrder { get; set; }
        public double RunArea { get; set; }
        public bool Pal { get; set; }
        public bool Complete { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual ICollection<DownTime> DownTime { get; set; }
        public virtual ICollection<EndOfRun> EndOfRun { get; set; }
        public virtual ICollection<EndOfRunTPOFeeder> EndOfRunTPOFeeder { get; set; }
        public virtual ICollection<IMLineScrap> IMLineScrap { get; set; }
        public virtual ICollection<IMProduction> IMProduction { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialAction { get; set; }
        public virtual ICollection<ScrimAction> ScrimAction { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRoll { get; set; }
        public virtual ICollection<TPOLineScrap> TPOLineScrap { get; set; }
    }
}
