CREATE TABLE [dbo].[QCKickout] (
    [ID]                 INT            IDENTITY (1, 1) NOT NULL,
    [LotID]              INT            NOT NULL,
    [PlantID]            INT            NOT NULL,
    [ProductID]          INT            NOT NULL,
    [RollID]             INT            NOT NULL,
    [LineID]             INT            NOT NULL,
    [ShiftID]            INT            NOT NULL,
    [QCTechID]           INT            NULL,
    [LeadOperatorID]     INT            NULL,
    [SupervisorID]       INT            NULL,
    [KickoutDate]        DATETIME       NOT NULL,
    [RollLengthFT]       FLOAT (53)     NULL,
    [RollLengthIN]       FLOAT (53)     NULL,
    [RollLengthFTSet]    FLOAT (53)     NULL,
    [RollLengthINSet]    FLOAT (53)     NULL,
    [TackLine]           FLOAT (53)     NULL,
    [LapLine]            FLOAT (53)     NULL,
    [WeldLine]           FLOAT (53)     NULL,
    [DateLine]           FLOAT (53)     NULL,
    [WeldToLapLine]      FLOAT (53)     NULL,
    [CutStraight]        BIT            NULL,
    [SheetFlat]          BIT            NULL,
    [GESpec]             BIT            NULL,
    [EdgeFlat]           BIT            NULL,
    [UnwindStraight]     BIT            NULL,
    [CoreWrinkles]       BIT            NULL,
    [PrintOK]            BIT            NULL,
    [ThickAlarmVerified] BIT            NULL,
    [CameraVerified]     BIT            NULL,
    [Passed]             BIT            NULL,
    [Comment]            NVARCHAR (MAX) NULL,
    [DateEntered]        DATETIME       NOT NULL,
    [EnteredBy]          NVARCHAR (100) NOT NULL,
    [LastModified]       DATETIME       NOT NULL,
    [ModifiedBy]         NVARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_QCKickout_LeadOperatorID] FOREIGN KEY ([LeadOperatorID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_QCKickout_Plant] FOREIGN KEY ([PlantID]) REFERENCES [dbo].[Plant] ([ID]),
    CONSTRAINT [FK_QCKickout_ProductionShift] FOREIGN KEY ([ShiftID]) REFERENCES [dbo].[ProductionShift] ([ID]),
    CONSTRAINT [FK_QCKickout_QCTechID] FOREIGN KEY ([QCTechID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_QCKickout_SupervisorID] FOREIGN KEY ([SupervisorID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_QCKickout_TPOCProductRoll] FOREIGN KEY ([RollID]) REFERENCES [dbo].[TPOCProductRoll] ([ID])
);

