CREATE TABLE [dbo].[QCRedHold] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [PlantID]             INT            NOT NULL,
    [LineID]              INT            NOT NULL,
    [RollID]              INT            NOT NULL,
    [FailPropertyID]      INT            NULL,
    [ProductID]           INT            NOT NULL,
    [LotNumber]           INT            NOT NULL,
    [HoldLotNumber]       INT            NULL,
    [QCTechID]            INT            NULL,
    [LeadOperatorID]      INT            NULL,
    [SupervisorID]        INT            NULL,
    [ManagerID]           INT            NULL,
    [RedDate]             DATE           NOT NULL,
    [Zone]                NVARCHAR (50)  NULL,
    [RedComments]         NVARCHAR (MAX) NULL,
    [RedCorrectionAction] NVARCHAR (500) NULL,
    [HoldDate]            DATE           NULL,
    [HoldComments]        NVARCHAR (MAX) NULL,
    [ManagerDate]         DATE           NULL,
    [ManagerComments]     NVARCHAR (MAX) NULL,
    [PrimeRolls]          FLOAT (53)     NOT NULL,
    [PrimeArea]           FLOAT (53)     NOT NULL,
    [ReworkRolls]         FLOAT (53)     NOT NULL,
    [ReworkArea]          FLOAT (53)     NOT NULL,
    [SCRolls]             FLOAT (53)     NOT NULL,
    [SCArea]              FLOAT (53)     NOT NULL,
    [DateEntered]         DATETIME       NOT NULL,
    [EnteredBy]           NVARCHAR (100) NOT NULL,
    [LastModified]        DATETIME       NOT NULL,
    [ModifiedBy]          NVARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_QCRedHold_FailProperty] FOREIGN KEY ([FailPropertyID]) REFERENCES [dbo].[FailProperty] ([ID]),
    CONSTRAINT [FK_QCRedHold_LeadOperatorID] FOREIGN KEY ([LeadOperatorID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_QCRedHold_ManagerID] FOREIGN KEY ([ManagerID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_QCRedHold_Plant] FOREIGN KEY ([PlantID]) REFERENCES [dbo].[Plant] ([ID]),
    CONSTRAINT [FK_QCRedHold_QCTechID] FOREIGN KEY ([QCTechID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_QCRedHold_SupervisorID] FOREIGN KEY ([SupervisorID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_QCRedHold_TPOCProductRoll] FOREIGN KEY ([RollID]) REFERENCES [dbo].[TPOCProductRoll] ([ID])
);

