CREATE TABLE [dbo].[RawMaterialQC] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [PlantID]               INT            NOT NULL,
    [QCTechUserID]          INT            NULL,
    [SpecGrav]              FLOAT (53)     NULL,
    [ColorCoA]              FLOAT (53)     NULL,
    [ColorFS]               FLOAT (53)     NULL,
    [MFCoA]                 FLOAT (53)     NULL,
    [MFFS]                  FLOAT (53)     NULL,
    [ACCoA]                 FLOAT (53)     NULL,
    [ACFS]                  FLOAT (53)     NULL,
    [MoistCoA]              FLOAT (53)     NULL,
    [MoistFS]               FLOAT (53)     NULL,
    [CBCoA]                 FLOAT (53)     NULL,
    [CBFS]                  FLOAT (53)     NULL,
    [BoxCarTested]          NVARCHAR (50)  NULL,
    [Comments]              NVARCHAR (MAX) NULL,
    [DateEntered]           DATETIME       NOT NULL,
    [EnteredBy]             NVARCHAR (100) NOT NULL,
    [LastModified]          DATETIME       NOT NULL,
    [ModifiedBy]            NVARCHAR (100) NOT NULL,
    [RawMaterialReceivedID] INT            DEFAULT ((1)) NOT NULL,
    [QCVisualInspectionID]  INT            DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_RawMaterialQC_Plant] FOREIGN KEY ([PlantID]) REFERENCES [dbo].[Plant] ([ID]),
    CONSTRAINT [FK_RawMaterialQC_QCTechUser] FOREIGN KEY ([QCTechUserID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_RawMaterialQC_QCVisualInspectionType] FOREIGN KEY ([QCVisualInspectionID]) REFERENCES [dbo].[QCVisualInspectionType] ([ID]),
    CONSTRAINT [FK_RawMaterialQC_RawMaterialReceived] FOREIGN KEY ([RawMaterialReceivedID]) REFERENCES [dbo].[RawMaterialReceived] ([ID])
);

