CREATE TABLE [dbo].[RawMaterialQCRedHold] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [PlantID]               INT            NOT NULL,
    [RawMaterialReceivedID] INT            NOT NULL,
    [FailPropertyID]        INT            NULL,
    [HoldLotNumber]         NVARCHAR (50)  NULL,
    [QCTechID]              INT            NULL,
    [LeadOperatorID]        INT            NULL,
    [SupervisorID]          INT            NULL,
    [ManagerID]             INT            NULL,
    [RedDate]               DATE           NULL,
    [Zone]                  NVARCHAR (50)  NULL,
    [RedComments]           NVARCHAR (MAX) NULL,
    [RedCorrectionAction]   NVARCHAR (500) NULL,
    [HoldDate]              DATE           NULL,
    [HoldComments]          NVARCHAR (MAX) NULL,
    [ManagerDate]           DATE           NULL,
    [ManagerComments]       NVARCHAR (MAX) NULL,
    [PrimeBoxCar]           FLOAT (53)     NOT NULL,
    [PrimeUOM]              FLOAT (53)     NOT NULL,
    [ReworkBoxCar]          FLOAT (53)     NOT NULL,
    [ReworkUOM]             FLOAT (53)     NOT NULL,
    [ScrapBoxCar]           FLOAT (53)     NOT NULL,
    [ScrapUOM]              FLOAT (53)     NOT NULL,
    [DateEntered]           DATETIME       NOT NULL,
    [EnteredBy]             NVARCHAR (100) NOT NULL,
    [LastModified]          DATETIME       NOT NULL,
    [ModifiedBy]            NVARCHAR (100) NOT NULL,
    [RawMaterialQCID]       INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_RawMaterialQCRedHold_FailProperty] FOREIGN KEY ([FailPropertyID]) REFERENCES [dbo].[FailProperty] ([ID]),
    CONSTRAINT [FK_RawMaterialQCRedHold_LeadOperatorID] FOREIGN KEY ([LeadOperatorID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_RawMaterialQCRedHold_ManagerID] FOREIGN KEY ([ManagerID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_RawMaterialQCRedHold_Plant] FOREIGN KEY ([PlantID]) REFERENCES [dbo].[Plant] ([ID]),
    CONSTRAINT [FK_RawMaterialQCRedHold_QCTechID] FOREIGN KEY ([QCTechID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_RawMaterialQCRedHold_RawMaterialQCID] FOREIGN KEY ([RawMaterialQCID]) REFERENCES [dbo].[RawMaterialQC] ([ID]),
    CONSTRAINT [FK_RawMaterialQCRedHold_RawMaterialReceived] FOREIGN KEY ([RawMaterialReceivedID]) REFERENCES [dbo].[RawMaterialReceived] ([ID]),
    CONSTRAINT [FK_RawMaterialQCRedHold_SupervisorID] FOREIGN KEY ([SupervisorID]) REFERENCES [dbo].[User] ([ID])
);

