CREATE TABLE [dbo].[RawMaterialTest] (
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
    [PlantID]          INT            NOT NULL,
    [UseColorTest]     BIT            NOT NULL,
    [ColorLimitTypeID] INT            NULL,
    [ColorLimit1]      FLOAT (53)     NULL,
    [ColorLimit2]      FLOAT (53)     NULL,
    [UseMFTest]        BIT            NOT NULL,
    [MFLimitTypeID]    INT            NULL,
    [MFLimit1]         FLOAT (53)     NULL,
    [MFLimit2]         FLOAT (53)     NULL,
    [UseACTest]        BIT            NOT NULL,
    [ACLimitTypeID]    INT            NULL,
    [ACLimit1]         FLOAT (53)     NULL,
    [ACLimit2]         FLOAT (53)     NULL,
    [UseMoistTest]     BIT            NOT NULL,
    [MoistLimitTypeID] INT            NULL,
    [MoistLimit1]      FLOAT (53)     NULL,
    [MoistLimit2]      FLOAT (53)     NULL,
    [UseCBTest]        BIT            NOT NULL,
    [CBLimitTypeID]    INT            NULL,
    [CBLimit1]         FLOAT (53)     NULL,
    [CBLimit2]         FLOAT (53)     NULL,
    [UseSpecGrav]      BIT            NULL,
    [UseVisual]        BIT            NULL,
    [TestFrequency]    NVARCHAR (50)  NULL,
    [DateEntered]      DATETIME       NOT NULL,
    [EnteredBy]        NVARCHAR (100) NOT NULL,
    [LastModified]     DATETIME       NOT NULL,
    [ModifiedBy]       NVARCHAR (100) NOT NULL,
    [RawMaterialID]    INT            DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_RawMaterialTest_ACLimitType] FOREIGN KEY ([ACLimitTypeID]) REFERENCES [dbo].[TestLimitType] ([ID]),
    CONSTRAINT [FK_RawMaterialTest_CBLimitType] FOREIGN KEY ([CBLimitTypeID]) REFERENCES [dbo].[TestLimitType] ([ID]),
    CONSTRAINT [FK_RawMaterialTest_ColorLimitType] FOREIGN KEY ([ColorLimitTypeID]) REFERENCES [dbo].[TestLimitType] ([ID]),
    CONSTRAINT [FK_RawMaterialTest_MFLimitType] FOREIGN KEY ([MFLimitTypeID]) REFERENCES [dbo].[TestLimitType] ([ID]),
    CONSTRAINT [FK_RawMaterialTest_MoistLimitType] FOREIGN KEY ([MoistLimitTypeID]) REFERENCES [dbo].[TestLimitType] ([ID]),
    CONSTRAINT [FK_RawMaterialTest_Plant] FOREIGN KEY ([PlantID]) REFERENCES [dbo].[Plant] ([ID]),
    CONSTRAINT [FK_RawMaterialTest_RawMaterials] FOREIGN KEY ([RawMaterialID]) REFERENCES [dbo].[RawMaterials] ([ID])
);

