CREATE TABLE [dbo].[ScrimAction] (
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
    [PlantID]          INT            NOT NULL,
    [LineID]           INT            NULL,
    [ShiftID]          INT            NULL,
    [WorkOrderID]      INT            NULL,
    [RollID]           INT            NULL,
    [ScrimRollID]      INT            NOT NULL,
    [TypeID]           INT            NOT NULL,
    [ReasonID]         INT            NULL,
    [UserID]           INT            NOT NULL,
    [ActionLength]     FLOAT (53)     NOT NULL,
    [ActionWeight]     FLOAT (53)     NOT NULL,
    [StartLength]      FLOAT (53)     NOT NULL,
    [StartWeight]      FLOAT (53)     NOT NULL,
    [EndLength]        FLOAT (53)     NOT NULL,
    [EndWeight]        FLOAT (53)     NOT NULL,
    [ActionDate]       DATETIME       NOT NULL,
    [FleeceProd]       BIT            NULL,
    [DateEntered]      DATETIME       NOT NULL,
    [EnteredBy]        NVARCHAR (100) NOT NULL,
    [LastModified]     DATETIME       NOT NULL,
    [ModifiedBy]       NVARCHAR (100) NOT NULL,
    [ActionReasonText] NVARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ScrimAction_Plant] FOREIGN KEY ([PlantID]) REFERENCES [dbo].[Plant] ([ID]),
    CONSTRAINT [FK_ScrimAction_ProductionShift] FOREIGN KEY ([ShiftID]) REFERENCES [dbo].[ProductionShift] ([ID]),
    CONSTRAINT [FK_ScrimAction_ScrimActionReason] FOREIGN KEY ([ReasonID]) REFERENCES [dbo].[ScrimActionReason] ([ID]),
    CONSTRAINT [FK_ScrimAction_ScrimActionType] FOREIGN KEY ([TypeID]) REFERENCES [dbo].[ScrimActionType] ([ID]),
    CONSTRAINT [FK_ScrimAction_ScrimRoll] FOREIGN KEY ([ScrimRollID]) REFERENCES [dbo].[ScrimRoll] ([ID]),
    CONSTRAINT [FK_ScrimAction_TPOCProductRoll] FOREIGN KEY ([RollID]) REFERENCES [dbo].[TPOCProductRoll] ([ID]),
    CONSTRAINT [FK_ScrimAction_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_ScrimAction_WorkOrder] FOREIGN KEY ([WorkOrderID]) REFERENCES [dbo].[WorkOrder] ([ID])
);

