CREATE TABLE [dbo].[TPOProducts] (
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
    [ProductCode]      NVARCHAR (20)  NOT NULL,
    [ProductDesc]      NVARCHAR (50)  NULL,
    [Thick]            FLOAT (53)     NOT NULL,
    [ThickUnit]        INT            NOT NULL,
    [Width]            FLOAT (53)     NOT NULL,
    [MasRollLength]    FLOAT (53)     NOT NULL,
    [ContRollLength]   FLOAT (53)     NOT NULL,
    [LengthWidthUnit]  INT            NOT NULL,
    [AreaUnit]         INT            NOT NULL,
    [WeightUnit]       INT            NOT NULL,
    [ScrimTypeID]      INT            NOT NULL,
    [QtyMade]          INT            NOT NULL,
    [WtperArea]        FLOAT (53)     NOT NULL,
    [ProductLabelID]   INT            NOT NULL,
    [FormNo]           INT            NOT NULL,
    [RollsPerLot]      INT            NOT NULL,
    [ThickTestUoM]     INT            NOT NULL,
    [WidthTestUoM]     INT            NOT NULL,
    [ForceTestUoM]     INT            NOT NULL,
    [ThickMin]         FLOAT (53)     NULL,
    [ThickMax]         FLOAT (53)     NULL,
    [WidthMin]         FLOAT (53)     NULL,
    [WidthMax]         FLOAT (53)     NULL,
    [GEWidthMin]       FLOAT (53)     NULL,
    [GEWidthMax]       FLOAT (53)     NULL,
    [GEThicknessMin]   FLOAT (53)     NULL,
    [PlyAdhMin]        FLOAT (53)     NULL,
    [PlyAdhAvg]        FLOAT (53)     NULL,
    [ProductCapCoreID] INT            NOT NULL,
    [ProductGrabID]    INT            NOT NULL,
    [DimStab]          FLOAT (53)     NULL,
    [UseSecThick]      BIT            NOT NULL,
    [ThickTestUoM2]    INT            NOT NULL,
    [WeldTestMin]      FLOAT (53)     NULL,
    [WeldTestMax]      FLOAT (53)     NULL,
    [ProductCEID]      INT            NOT NULL,
    [PunctMinTD]       FLOAT (53)     NULL,
    [PunctUoM]         INT            NOT NULL,
    [ThickAvgMin]      FLOAT (53)     NULL,
    [ThickAvgMax]      FLOAT (53)     NULL,
    [RollsPerLotPal]   INT            NOT NULL,
    [IsREPEL]          BIT            NOT NULL,
    [ThickAvg]         FLOAT (53)     NULL,
    [ProductDimID]     INT            NOT NULL,
    [Active]           BIT            NOT NULL,
    [PlantID]          INT            NOT NULL,
    [EnteredBy]        NVARCHAR (100) NOT NULL,
    [DateEntered]      DATETIME       NOT NULL,
    [ModifiedBy]       NVARCHAR (100) NOT NULL,
    [LastModified]     DATETIME       NOT NULL,
    CONSTRAINT [PK_TPOProducts] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TPOProducts_Plant] FOREIGN KEY ([PlantID]) REFERENCES [dbo].[Plant] ([ID]),
    CONSTRAINT [FK_TPOProducts_ProductCapCoreDetail] FOREIGN KEY ([ProductCapCoreID]) REFERENCES [dbo].[TPOProductCapCoreDetail] ([ID]),
    CONSTRAINT [FK_TPOProducts_ProductCEDetail] FOREIGN KEY ([ProductCEID]) REFERENCES [dbo].[TPOProductCEDetail] ([ID]),
    CONSTRAINT [FK_TPOProducts_ProductDimDetail] FOREIGN KEY ([ProductDimID]) REFERENCES [dbo].[TPOProductDimDetail] ([ID]),
    CONSTRAINT [FK_TPOProducts_ProductGrabDetail] FOREIGN KEY ([ProductGrabID]) REFERENCES [dbo].[TPOProductGrabDetail] ([ID]),
    CONSTRAINT [FK_TPOProducts_ProductLabelDetail] FOREIGN KEY ([ProductLabelID]) REFERENCES [dbo].[TPOProductLabelDetail] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure] FOREIGN KEY ([ThickUnit]) REFERENCES [dbo].[UnitOfMeasure] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure1] FOREIGN KEY ([LengthWidthUnit]) REFERENCES [dbo].[UnitOfMeasure] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure2] FOREIGN KEY ([AreaUnit]) REFERENCES [dbo].[UnitOfMeasure] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure3] FOREIGN KEY ([ThickTestUoM]) REFERENCES [dbo].[UnitOfMeasure] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure4] FOREIGN KEY ([WidthTestUoM]) REFERENCES [dbo].[UnitOfMeasure] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure5] FOREIGN KEY ([ForceTestUoM]) REFERENCES [dbo].[UnitOfMeasure] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure6] FOREIGN KEY ([ThickTestUoM2]) REFERENCES [dbo].[UnitOfMeasure] ([ID]),
    CONSTRAINT [FK_TPOProducts_UnitOfMeasure7] FOREIGN KEY ([PunctUoM]) REFERENCES [dbo].[UnitOfMeasure] ([ID])
);

