IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'webpages_RolesSecurityTasks')
BEGIN
	DELETE FROM [dbo].[webpages_RolesSecurityTasks]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SecurityTask')
BEGIN
	DELETE FROM [dbo].[SecurityTask]
END
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SecurityTask')
BEGIN
	-- LEGACY SUPPORT 
	-- TODO: Remove
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name],	[Active])
	VALUES  (500, 'Log In', 1)
	,		(510, 'Systems Administrator', 1)
	,		(520, 'QC Lab Tech', 1)
	,		(530, 'Lead Operator', 1)
	,		(540, 'Supervisor', 1)
	,		(550, 'Manager', 1)


	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (1, 'Raw Material Receipts', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (2, 'Raw Material Receipts ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (3, 'Delete Raw Material Receipts', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (4, 'Delete Raw Material Receipts ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (5, 'Raw Material QC Tests', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (6, 'Raw Material QC Tests ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (7, 'Edit QC Test Results', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (8, 'Edit QC Test Results ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (9, 'Raw Material Lots', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (10, 'Raw Material Lots ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (11, 'Edit Current Raw Material', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (12, 'Edit Current Raw Material ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (13, 'Roll Receipts', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (14, 'Roll Receipts ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (15, 'Set Scrim/Release Liner Rolls', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (16, 'Set Scrim/Release Liner Rolls ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (17, 'Edit Current (Scrim) Roll', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (18, 'Edit Current (Scrim) Roll ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (19, 'Equipment Run Time', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (20, 'Equipment Run Time ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (21, 'Work Orders', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (22, 'Work Orders ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (23, 'Work Order Status Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (24, 'Work Order Status Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (25, 'Production Schedule', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (26, 'Production Schedule ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (27, 'Monthly Production Budget', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (28, 'Monthly Production Budget ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (29, 'TPO Production', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (30, 'TPO Production ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (31, 'TPO Production Entry', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (32, 'TPO Production Entry ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (33, 'Set Current Raw Material Lots', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (34, 'Set Current Raw Material Lots ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (35, 'Set Current Scrim Rolls', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (36, 'Set Current Scrim Rolls ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (37, 'Show QC Test For Roll', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (38, 'Show QC Test For Roll ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (39, 'Edit TPO Production Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (40, 'Edit TPO Production Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (41, 'Rewind Operations', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (42, 'Rewind Operations ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (43, 'Rewind Production Entry', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (44, 'Rewind Production Entry ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (45, 'Rework Operations', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (46, 'Rework Operations ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (47, 'Rework Production Entry', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (48, 'Rework Production Entry ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (49, 'Reclaim Operations', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (50, 'Reclaim Operations ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (51, 'Reclaim Production Entry', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (52, 'Reclaim Production Entry ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (53, 'Injection Molding', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (54, 'Injection Molding ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (55, 'Injection Molding Prod Entry', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (56, 'Injection Molding Prod Entry ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (57, 'Coater Operations', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (58, 'Coater Operations ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (59, 'Edit Production Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (60, 'Edit Production Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (61, 'QC - Raw Material QC Tests', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (62, 'QC - Raw Material QC Tests ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (63, 'QC - TPO QC Tests', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (64, 'QC - TPO QC Tests ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (65, 'QC - QC Tests Enter New Test', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (66, 'QC - QC Tests Enter New Test ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (67, 'QC - QC Tests View/Edit Previous Test', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (68, 'QC - QC Tests View/Edit Previous Test ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (69, 'QC - QC Tests Red/Hold Form', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (70, 'QC - QC Tests Red/Hold Form ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (71, 'QC - Kickout Inspection', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (72, 'QC - Kickout Inspection ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (73, 'QC - Enter New Kickout Inspection', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (74, 'QC - Enter New Kickout Inspection ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (75, 'QC - View/Edit Previous Kickout Inspection', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (76, 'QC - View/Edit Previous Kickout Inspection ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (77, 'QC - Molding QC Tests', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (78, 'QC - Molding QC Tests ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (79, 'QC - Molding QC Tests - Enter New Test', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (80, 'QC - Molding QC Tests - Enter New Test ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (81, 'QC - Molding QC Tests - View Edit Previous Est', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (82, 'QC - Molding QC Tests - View/Edit Previous Est ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (83, 'TPO Products Standard Costs', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (84, 'TPO Products Standard Costs ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (85, 'Reporting - TPO Prod Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (86, 'Reporting - TPO Prod Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (87, 'Reporting - TPO Prod Totals', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (88, 'Reporting - TPO Prod Totals ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (89, 'Reporting - Production Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (90, 'Reporting - Production Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (91, 'Reporting - Production Summary With Shift Comments', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (92, 'Reporting - Production Summary With Shift Comments ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (93, 'Reporting - Work Order Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (94, 'Reporting - Work Order Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (95, 'Reporting - Calendar Date Production Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (96, 'Reporting - Calendar Date Production Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (97, 'Reporting - TPO Daily Run Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (98, 'Reporting - TPO Daily Run Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (99, 'Reporting - TPO Production by Width', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (100, 'Reporting - TPO Production by Width ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (101, 'Reporting - Weight Analysis Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (102, 'Reporting - Weight Analysis Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (103, 'Reporting - TPO Roll Averages', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (104, 'Reporting - TPO Roll Averages ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (105, 'Reporting - TPO Roll Mass/Area', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (106, 'Reporting - TPO Roll Mass/Area ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (107, 'Reporting - TPO Weekly Performance Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (108, 'Reporting - TPO Weekly Performance Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (109, 'Reporting - TPO Master Roll Usage', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (110, 'Reporting - TPO Master Roll Usage ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (111, 'Reporting - TPO Master Roll Usage Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (112, 'Reporting - TPO Master Roll Usage Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (113, 'Reporting - TPO Master Roll Usage Detail', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (114, 'Reporting - TPO Master Roll Usage Detail ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (115, 'Reporting - Monthly Productivity Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (116, 'Reporting - Monthly Productivity Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (117, 'Reporting - Lot Verification Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (118, 'Reporting - Lot Verification Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (119, 'Reporting - Tiny Term Production Entry', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (120, 'Reporting - Tiny Term Production Entry ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (121, 'Reporting - 605 Report Data', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (122, 'Reporting - 605 Report Data ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (123, 'Reporting - Tiny Term Verification', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (124, 'Reporting - Tiny Term Verification ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (125, 'Reporting - Production End of Run Scrim Used/Edge Trim', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (126, 'Reporting - Production End of Run Scrim Used/Edge Trim ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (127, 'Reporting - Molding Prod Reports', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (128, 'Reporting - Molding Prod Reports ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (129, 'Reporting - Molding Production Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (130, 'Reporting - Molding Production Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (131, 'Reporting - Molding Production Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (132, 'Reporting - Molding Production Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (133, 'Reporting - Molding Production Summary With Shift Comments', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (134, 'Reporting - Molding Production Summary With Shift Comments ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (135, 'Reporting - Molding Work Order Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (136, 'Reporting - Molding Work Order Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (137, 'Reporting - Molding Lot Verification Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (138, 'Reporting - Molding Lot Verification Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (139, 'Reporting - Reclaim Reports', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (140, 'Reporting - Reclaim Reports ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (141, 'Reporting - Reclaim Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (142, 'Reporting - Reclaim Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (143, 'Reporting - Rework Reports', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (144, 'Reporting - Rework Reports ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (145, 'Reporting - Rework Stats Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (146, 'Reporting - Rework Stats Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (147, 'Reporting - Rework Roll Conversion Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (148, 'Reporting - Rework Roll Conversion Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (149, 'Reporting - Rework Roll Conversion Report Detail', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (150, 'Reporting - Rework Roll Conversion Report Detail ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (151, 'Reporting - Rework Roll Conversion Report Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (152, 'Reporting - Rework Roll Conversion Report Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (153, 'Reporting - Rework Prime Roll Conversion Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (154, 'Reporting - Rework Prime Roll Conversion Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (155, 'Reporting - Rework Prime Roll Conversion Report Detail', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (156, 'Reporting - Rework Prime Roll Conversion Report Detail ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (157, 'Reporting - Rework Prime Roll Conversion Report Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (158, 'Reporting - Rework Prime Roll Conversion Report Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (159, 'Reporting - Rework Slip Sheet Created Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (160, 'Reporting - Rework Slip Sheet Created Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (161, 'Reporting - Rework Slip Sheet Created Report Detail', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (162, 'Reporting - Rework Slip Sheet Created Report Detail ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (163, 'Reporting - Rework Slip Sheet Created Report Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (164, 'Reporting - Rework Slip Sheet Created Report Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (165, 'Reporting - Scrap Reports', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (166, 'Reporting - Scrap Reports ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (167, 'Reporting - TPO Scrap Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (168, 'Reporting - TPO Scrap Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (169, 'Reporting - TPO Scrap by Product', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (170, 'Reporting - TPO Scrap by Product ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (171, 'Reporting - TPO Scrap Pivot Table', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (172, 'Reporting - TPO Scrap Pivot Table ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (173, 'Reporting - TPO Scrap Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (174, 'Reporting - TPO Scrap Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (175, 'Reporting - Downtime Reports', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (176, 'Reporting - Downtime Reports ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (177, 'Reporting - Downtime Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (178, 'Reporting - Downtime Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (179, 'Reporting - Downtime Pivot Table', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (180, 'Reporting - Downtime Pivot Table ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (181, 'Reporting - Downtime Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (182, 'Reporting - Downtime Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (183, 'Reporting - Raw Materials', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (184, 'Reporting - Raw Materials ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (185, 'Reporting - Raw Material Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (186, 'Reporting - Raw Material Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (187, 'Reporting - Raw Material Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (188, 'Reporting - Raw Material Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (189, 'Reporting - Raw Material Stock Level', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (190, 'Reporting - Raw Material Stock Level ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (191, 'Reporting - Raw Material Lots', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (192, 'Reporting - Raw Material Lots ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (193, 'Reporting - Find Raw Material Lots Used', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (194, 'Reporting - Find Raw Material Lots Used ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (195, 'Reporting - Find Products Made From a RM Lot', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (196, 'Reporting - Find Products Made From a RM Lot ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (197, 'Reporting - Scrim', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (198, 'Reporting - Scrim ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (199, 'Reporting - Scrim Entries', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (200, 'Reporting - Scrim Entries ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (201, 'Reporting - Scrim Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (202, 'Reporting - Scrim Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (203, 'Reporting - Scrim Stock Level', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (204, 'Reporting - Scrim Stock Level ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (205, 'Reporting - Scrim Rolls', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (206, 'Reporting - Scrim Rolls ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (207, 'Reporting - Find TPO Rolls Made with a Scrim Roll', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (208, 'Reporting - Find TPO Rolls Made with a Scrim Roll ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (209, 'Reporting - QC', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (210, 'Reporting - QC -ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (211, 'Reporting - QC -Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (212, 'Reporting - QC -Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (213, 'Reporting - Kickout Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (214, 'Reporting - Kickout Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (215, 'Reporting - Kickout Rolls Length/Weight', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (216, 'Reporting - Kickout Rolls Length/Weight ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (217, 'Reporting - QC - EOM Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (218, 'Reporting - QC - EOM Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (219, 'Reporting - QC - Individual Thickness Readings', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (220, 'Reporting - QC - Individual Thickness Readings ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (221, 'Reporting - QC - Individual Cap and Core Thickness Readings', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (222, 'Reporting - QC - Individual Cap and Core Thickness Readings ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (223, 'Reporting - QC - Color Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (224, 'Reporting - QC - Color Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (225, 'Reporting - QC - Weld Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (226, 'Reporting - QC - Weld Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (227, 'Reporting - QC - fPP Summary Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (228, 'Reporting - QC - fPP Summary Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (229, 'Reporting - QC - fPP CoA Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (230, 'Reporting - QC - fPP CoA Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (231, 'Reporting - QC - P.Green Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (232, 'Reporting - QC - P.Green Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (233, 'Reporting - QC - Injection Molding QC Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (234, 'Reporting - QC - Injection Molding QC Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (235, 'Reporting - QC - Red/Hold Form Reports', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (236, 'Reporting - QC - Red/Hold Form Reports ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (237, 'Reporting - QC - Red/Hold Forms Issued', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (238, 'Reporting - QC - Red/Hold Forms Issued ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (239, 'Reporting - QC - Red/Hold Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (240, 'Reporting - QC - Red/Hold Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (241, 'Reporting - QC - O/U Scrim Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (242, 'Reporting - QC - O/U Scrim Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (243, 'Reporting - QC - Raw Material QC Summary', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (244, 'Reporting - QC - Raw Material QC Summary ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (245, 'Reporting - Accounting', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (246, 'Reporting - Accounting ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (247, 'Reporting - Accounting Daily Usage Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (248, 'Reporting - Accounting Daily Usage Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (249, 'Reporting - Accounting WIP Report', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (250, 'Reporting - Accounting WIP Report ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (251, 'Reporting - Accounting Current TPO Standard Costs', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (252, 'Reporting - Accounting Current TPO Standard Costs ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (253, 'Reporting - Production Schedule', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (254, 'Reporting - Production Schedule ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (255, 'System Admin - System Setup', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (256, 'System Admin - System Setup ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (257, 'System Admin - Set User Access Levels', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (258, 'System Admin - Set User Access Levels ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (259, 'System Admin - Production Lines', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (260, 'System Admin - Production Lines ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (261, 'System Admin - Prod Lines Report Ordering', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (262, 'System Admin - Prod Lines Report Ordering ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (263, 'System Admin - Set Production Shifts', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (264, 'System Admin - Set Production Shifts ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (265, 'System Admin - Set Default Unit of Measures', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (266, 'System Admin - Set Default Unit of Measures ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (267, 'System Admin - Downtime Codes Setup', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (268, 'System Admin - Downtime Codes Setup ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (269, 'System Admin - Scrap Codes Setup', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (270, 'System Admin - Scrap Codes Setup ReadOnly', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (271, 'System Admin - Change Passwords', 1)
	INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (272, 'System Admin - Change Passwords ReadOnly', 1)
	--INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (273, 'System Admin - Set Edit Prod Screen Password', 1)
	--INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (274, 'System Admin - Set Edit Prod Screen Password ReadOnly', 1)
	--INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (275, 'System Admin - Set RM QC Unlock Fields PW', 1)
	--INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (276, 'System Admin - Set RM QC Unlock Fields PW ReadOnly', 1)
	--INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (277, 'Set Delete RM Receipt PW', 1)
	--INSERT INTO [dbo].[SecurityTask] ([SecurityTaskId], [Name], [Active]) VALUES (278, 'Set Delete RM Receipt PW ReadOnly', 1)

END
GO


