//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMProd
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int ProdLineID { get; set; }
        public int IMProductID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime ProdDate { get; set; }
        public string ProdShift { get; set; }
        public int PartsCarton { get; set; }
        public double CartonWeight { get; set; }
        public int WeightUOM { get; set; }
        public int BatchNumber { get; set; }
        public int IMQCID { get; set; }
        public int WorkOrderID { get; set; }
        public string Comment { get; set; }
        public int PlantID { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<System.DateTime> AdhesionManufacturesDate { get; set; }
    
        public virtual IMProduct IMProduct { get; set; }
        public virtual IMQC IMQC { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
