//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public Plant()
        {
            this.ProductionShifts = new HashSet<ProductionShift>();
            this.RawMaterialActions = new HashSet<RawMaterialAction>();
            this.RawMaterialQCs = new HashSet<RawMaterialQC>();
            this.RawMaterialReceiveds = new HashSet<RawMaterialReceived>();
            this.RawMaterialTests = new HashSet<RawMaterialTest>();
            this.ScrimActionTypes = new HashSet<ScrimActionType>();
            this.ScrimTypes = new HashSet<ScrimType>();
            this.Users = new HashSet<User>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.ScrimActions = new HashSet<ScrimAction>();
            this.ScrimRolls = new HashSet<ScrimRoll>();
            this.TPOCProductRolls = new HashSet<TPOCProductRoll>();
            this.TPOCurrentScrims = new HashSet<TPOCurrentScrim>();
            this.QCRedHolds = new HashSet<QCRedHold>();
            this.RawMaterialQCRedHolds = new HashSet<RawMaterialQCRedHold>();
            this.TPOCurrentRawMaterials = new HashSet<TPOCurrentRawMaterial>();
            this.IMProds = new HashSet<IMProd>();
            this.IMProducts = new HashSet<IMProduct>();
            this.IMQCs = new HashSet<IMQC>();
            this.ProdDteChngs = new HashSet<ProdDteChng>();
            this.ProdLines = new HashSet<ProdLine>();
            this.ProdLinesPerforms = new HashSet<ProdLinesPerform>();
            this.ProdLinesPerformProds = new HashSet<ProdLinesPerformProd>();
            this.ProdSupervisorOnShifts = new HashSet<ProdSupervisorOnShift>();
            this.ProductionBudgets = new HashSet<ProductionBudget>();
            this.ProductionLineSchedules = new HashSet<ProductionLineSchedule>();
            this.ProductionShiftUses = new HashSet<ProductionShiftUse>();
            this.QCKickouts = new HashSet<QCKickout>();
            this.QCPrintSpecifications = new HashSet<QCPrintSpecification>();
            this.RawMaterials = new HashSet<RawMaterial>();
            this.RawMaterialVendors = new HashSet<RawMaterialVendor>();
            this.TPOFormulationLineProducts = new HashSet<TPOFormulationLineProduct>();
            this.TPOFormulationRawMaterials = new HashSet<TPOFormulationRawMaterial>();
            this.TPOFormulations = new HashSet<TPOFormulation>();
            this.TPOProductStandardCosts = new HashSet<TPOProductStandardCost>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<ProductionShift> ProductionShifts { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialActions { get; set; }
        public virtual ICollection<RawMaterialQC> RawMaterialQCs { get; set; }
        public virtual ICollection<RawMaterialReceived> RawMaterialReceiveds { get; set; }
        public virtual ICollection<RawMaterialTest> RawMaterialTests { get; set; }
        public virtual ICollection<ScrimActionType> ScrimActionTypes { get; set; }
        public virtual ICollection<ScrimType> ScrimTypes { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual ICollection<ScrimAction> ScrimActions { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRolls { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual ICollection<TPOCurrentScrim> TPOCurrentScrims { get; set; }
        public virtual ICollection<QCRedHold> QCRedHolds { get; set; }
        public virtual ICollection<RawMaterialQCRedHold> RawMaterialQCRedHolds { get; set; }
        public virtual ICollection<TPOCurrentRawMaterial> TPOCurrentRawMaterials { get; set; }
        public virtual ICollection<IMProd> IMProds { get; set; }
        public virtual ICollection<IMProduct> IMProducts { get; set; }
        public virtual ICollection<IMQC> IMQCs { get; set; }
        public virtual ICollection<ProdDteChng> ProdDteChngs { get; set; }
        public virtual ICollection<ProdLine> ProdLines { get; set; }
        public virtual ICollection<ProdLinesPerform> ProdLinesPerforms { get; set; }
        public virtual ICollection<ProdLinesPerformProd> ProdLinesPerformProds { get; set; }
        public virtual ICollection<ProdSupervisorOnShift> ProdSupervisorOnShifts { get; set; }
        public virtual ICollection<ProductionBudget> ProductionBudgets { get; set; }
        public virtual ICollection<ProductionLineSchedule> ProductionLineSchedules { get; set; }
        public virtual ICollection<ProductionShiftUse> ProductionShiftUses { get; set; }
        public virtual ICollection<QCKickout> QCKickouts { get; set; }
        public virtual ICollection<QCPrintSpecification> QCPrintSpecifications { get; set; }
        public virtual ICollection<RawMaterial> RawMaterials { get; set; }
        public virtual ICollection<RawMaterialVendor> RawMaterialVendors { get; set; }
        public virtual ICollection<TPOFormulationLineProduct> TPOFormulationLineProducts { get; set; }
        public virtual ICollection<TPOFormulationRawMaterial> TPOFormulationRawMaterials { get; set; }
        public virtual ICollection<TPOFormulation> TPOFormulations { get; set; }
        public virtual ICollection<TPOProductStandardCost> TPOProductStandardCosts { get; set; }
    }
}
