//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdLinesPerformProd
    {
        public int ID { get; set; }
        public int LocID { get; set; }
        public int ProdLineID { get; set; }
        public int ProductID { get; set; }
        public double Throughput { get; set; }
        public System.DateTime DateChange { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual TPOProduct TPOProduct { get; set; }
    }
}
