//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdLine
    {
        public ProdLine()
        {
            this.IMProds = new HashSet<IMProd>();
            this.IMQCs = new HashSet<IMQC>();
            this.ProdLinesPerformProds = new HashSet<ProdLinesPerformProd>();
            this.RawMaterialActions = new HashSet<RawMaterialAction>();
            this.TPOFormulationLineProducts = new HashSet<TPOFormulationLineProduct>();
        }
    
        public int ID { get; set; }
        public string LineDescCode { get; set; }
        public string LineDesc { get; set; }
        public int LineTypeID { get; set; }
        public int LabelID { get; set; }
        public string CrntWOID { get; set; }
        public string TPOMorC { get; set; }
        public int RepOrder { get; set; }
        public string RCComp { get; set; }
        public int LocID { get; set; }
        public System.DateTime ModDate { get; set; }
        public int LineRollConfigID { get; set; }
    
        public virtual ICollection<IMProd> IMProds { get; set; }
        public virtual ICollection<IMQC> IMQCs { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ProdLineRollConfig ProdLineRollConfig { get; set; }
        public virtual ProdLineType ProdLineType { get; set; }
        public virtual ICollection<ProdLinesPerformProd> ProdLinesPerformProds { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialActions { get; set; }
        public virtual ICollection<TPOFormulationLineProduct> TPOFormulationLineProducts { get; set; }
    }
}
