//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdDteChng
    {
        public int ID { get; set; }
        public int LocID { get; set; }
        public string LineCode { get; set; }
        public int ChangeType { get; set; }
        public System.DateTime DateChange { get; set; }
        public System.DateTime RotationStart { get; set; }
    
        public virtual Plant Plant { get; set; }
    }
}
