//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdSupervisorOnShift
    {
        public int ID { get; set; }
        public int IDCode { get; set; }
        public int LocID { get; set; }
        public string LineIDCode { get; set; }
        public System.DateTime ProdDate { get; set; }
        public int ProdShiftID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateMod { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
    }
}
