//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionShift
    {
        public ProductionShift()
        {
            this.RawMaterialActions = new HashSet<RawMaterialAction>();
            this.ScrimActions = new HashSet<ScrimAction>();
            this.TPOCProductRolls = new HashSet<TPOCProductRoll>();
            this.ProdSupervisorOnShifts = new HashSet<ProdSupervisorOnShift>();
            this.ProductionLineSchedules = new HashSet<ProductionLineSchedule>();
            this.ProductionShiftUses = new HashSet<ProductionShiftUse>();
            this.QCKickouts = new HashSet<QCKickout>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int TypeID { get; set; }
        public string Code { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShiftType ProductionShiftType { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialActions { get; set; }
        public virtual ICollection<ScrimAction> ScrimActions { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual ICollection<ProdSupervisorOnShift> ProdSupervisorOnShifts { get; set; }
        public virtual ICollection<ProductionLineSchedule> ProductionLineSchedules { get; set; }
        public virtual ICollection<ProductionShiftUse> ProductionShiftUses { get; set; }
        public virtual ICollection<QCKickout> QCKickouts { get; set; }
    }
}
