//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdLineType
    {
        public ProdLineType()
        {
            this.ProdLines = new HashSet<ProdLine>();
        }
    
        public int ID { get; set; }
        public string ProdLineType1 { get; set; }
        public string ProdLineTypeDesc { get; set; }
        public int LineRollConfigID { get; set; }
    
        public virtual ProdLineRollConfig ProdLineRollConfig { get; set; }
        public virtual ICollection<ProdLine> ProdLines { get; set; }
        public virtual ProdLineType ProdLineType11 { get; set; }
        public virtual ProdLineType ProdLineType2 { get; set; }
    }
}
