//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialVendor
    {
        public RawMaterialVendor()
        {
            this.RawMaterials = new HashSet<RawMaterial>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public string Vendor { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<RawMaterial> RawMaterials { get; set; }
    }
}
