//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialReceived
    {
        public RawMaterialReceived()
        {
            this.RawMaterialQCRedHolds = new HashSet<RawMaterialQCRedHold>();
            this.TPOCurrentRawMaterials = new HashSet<TPOCurrentRawMaterial>();
            this.RawMaterialQCs = new HashSet<RawMaterialQC>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int RawMaterialID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public string LotNumber { get; set; }
        public string CoA { get; set; }
        public double QuantityShipped { get; set; }
        public double QuantityReceived { get; set; }
        public double QuantityNotReceived { get; set; }
        public double QuantityUsedThisLot { get; set; }
        public int ReceivedSizeLimitID { get; set; }
        public int UOMID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<RawMaterialQCRedHold> RawMaterialQCRedHolds { get; set; }
        public virtual ICollection<TPOCurrentRawMaterial> TPOCurrentRawMaterials { get; set; }
        public virtual ICollection<RawMaterialQC> RawMaterialQCs { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
