//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialSpecificGravity
    {
        public RawMaterialSpecificGravity()
        {
            this.RawMaterialSpecificGravityDetails = new HashSet<RawMaterialSpecificGravityDetail>();
        }
    
        public int ID { get; set; }
        public int RawMaterialQCID { get; set; }
        public Nullable<int> LabTechUserID { get; set; }
        public double DenIso { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual RawMaterialQC RawMaterialQC { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RawMaterialSpecificGravityDetail> RawMaterialSpecificGravityDetails { get; set; }
    }
}
