//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOExtruder
    {
        public TPOExtruder()
        {
            this.TPOFormulationRawMaterials = new HashSet<TPOFormulationRawMaterial>();
            this.TPOFormulations = new HashSet<TPOFormulation>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<TPOFormulationRawMaterial> TPOFormulationRawMaterials { get; set; }
        public virtual ICollection<TPOFormulation> TPOFormulations { get; set; }
    }
}
