//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOFormulationRawMaterial
    {
        public int ID { get; set; }
        public int TPOFormulationID { get; set; }
        public int TPOExtruderID { get; set; }
        public int FeedNumber { get; set; }
        public int RawMaterialID { get; set; }
        public double CompPerc { get; set; }
        public int PlantID { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual TPOExtruder TPOExtruder { get; set; }
        public virtual TPOFormulation TPOFormulation { get; set; }
    }
}
