//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPOMVCApplicationEntities : DbContext
    {
        public TPOMVCApplicationEntities()
            : base("name=TPOMVCApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<ProductionShift> ProductionShifts { get; set; }
        public virtual DbSet<ProductionShiftType> ProductionShiftTypes { get; set; }
        public virtual DbSet<RawMaterialAction> RawMaterialActions { get; set; }
        public virtual DbSet<RawMaterialActionReason> RawMaterialActionReasons { get; set; }
        public virtual DbSet<RawMaterialActionType> RawMaterialActionTypes { get; set; }
        public virtual DbSet<RawMaterialQC> RawMaterialQCs { get; set; }
        public virtual DbSet<RawMaterialReceived> RawMaterialReceiveds { get; set; }
        public virtual DbSet<RawMaterialTest> RawMaterialTests { get; set; }
        public virtual DbSet<ScrimActionReason> ScrimActionReasons { get; set; }
        public virtual DbSet<ScrimActionType> ScrimActionTypes { get; set; }
        public virtual DbSet<ScrimType> ScrimTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestLimitType> TestLimitTypes { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<UnitOfMeasureType> UnitOfMeasureTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleAssignment> RoleAssignments { get; set; }
        public virtual DbSet<ScrimAction> ScrimActions { get; set; }
        public virtual DbSet<ScrimRoll> ScrimRolls { get; set; }
        public virtual DbSet<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual DbSet<TPOCurrentScrim> TPOCurrentScrims { get; set; }
        public virtual DbSet<FailProperty> FailProperties { get; set; }
        public virtual DbSet<QCRedHold> QCRedHolds { get; set; }
        public virtual DbSet<RawMaterialQCRedHold> RawMaterialQCRedHolds { get; set; }
        public virtual DbSet<RawMaterialSpecificGravity> RawMaterialSpecificGravities { get; set; }
        public virtual DbSet<RawMaterialSpecificGravityDetail> RawMaterialSpecificGravityDetails { get; set; }
        public virtual DbSet<TPOCurrentRawMaterial> TPOCurrentRawMaterials { get; set; }
        public virtual DbSet<IMProd> IMProds { get; set; }
        public virtual DbSet<IMProduct> IMProducts { get; set; }
        public virtual DbSet<IMProductType> IMProductTypes { get; set; }
        public virtual DbSet<IMQC> IMQCs { get; set; }
        public virtual DbSet<ProdDteChng> ProdDteChngs { get; set; }
        public virtual DbSet<ProdLineRollConfig> ProdLineRollConfigs { get; set; }
        public virtual DbSet<ProdLine> ProdLines { get; set; }
        public virtual DbSet<ProdLinesPerform> ProdLinesPerforms { get; set; }
        public virtual DbSet<ProdLinesPerformProd> ProdLinesPerformProds { get; set; }
        public virtual DbSet<ProdLineType> ProdLineTypes { get; set; }
        public virtual DbSet<ProdSupervisorOnShift> ProdSupervisorOnShifts { get; set; }
        public virtual DbSet<ProductionBudget> ProductionBudgets { get; set; }
        public virtual DbSet<ProductionBudgetType> ProductionBudgetTypes { get; set; }
        public virtual DbSet<ProductionLineSchedule> ProductionLineSchedules { get; set; }
        public virtual DbSet<ProductionShiftUse> ProductionShiftUses { get; set; }
        public virtual DbSet<QCKickout> QCKickouts { get; set; }
        public virtual DbSet<QCPrintSpecification> QCPrintSpecifications { get; set; }
        public virtual DbSet<QCPrintSpecificationType> QCPrintSpecificationTypes { get; set; }
        public virtual DbSet<RawMaterial> RawMaterials { get; set; }
        public virtual DbSet<RawMaterialVendor> RawMaterialVendors { get; set; }
        public virtual DbSet<TPOExtruder> TPOExtruders { get; set; }
        public virtual DbSet<TPOFormulation> TPOFormulations { get; set; }
        public virtual DbSet<TPOFormulationLineProduct> TPOFormulationLineProducts { get; set; }
        public virtual DbSet<TPOFormulationRawMaterial> TPOFormulationRawMaterials { get; set; }
        public virtual DbSet<TPOProductCapCoreDetail> TPOProductCapCoreDetails { get; set; }
        public virtual DbSet<TPOProductCEDetail> TPOProductCEDetails { get; set; }
        public virtual DbSet<TPOProductDimDetail> TPOProductDimDetails { get; set; }
        public virtual DbSet<TPOProductGrabDetail> TPOProductGrabDetails { get; set; }
        public virtual DbSet<TPOProductLabelDetail> TPOProductLabelDetails { get; set; }
        public virtual DbSet<TPOProduct> TPOProducts { get; set; }
        public virtual DbSet<TPOProductStandardCost> TPOProductStandardCosts { get; set; }
    }
}
