//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOProductCEDetail
    {
        public TPOProductCEDetail()
        {
            this.TPOProducts = new HashSet<TPOProduct>();
        }
    
        public int ID { get; set; }
        public bool UseCELogo { get; set; }
        public Nullable<int> CEForceTestUoM { get; set; }
        public Nullable<double> CETensMinMD { get; set; }
        public Nullable<double> CEElongMinMD { get; set; }
        public Nullable<double> CETensMinTD { get; set; }
        public Nullable<double> CEElongMinTD { get; set; }
        public Nullable<double> CETearMinMD { get; set; }
        public Nullable<double> CETearMinTD { get; set; }
    
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts { get; set; }
    }
}
