//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public UnitOfMeasure()
        {
            this.ScrimTypes = new HashSet<ScrimType>();
            this.ScrimTypes1 = new HashSet<ScrimType>();
            this.ScrimTypes2 = new HashSet<ScrimType>();
            this.ScrimRolls = new HashSet<ScrimRoll>();
            this.ScrimRolls1 = new HashSet<ScrimRoll>();
            this.TPOCProductRolls = new HashSet<TPOCProductRoll>();
            this.TPOCProductRolls1 = new HashSet<TPOCProductRoll>();
            this.IMProds = new HashSet<IMProd>();
            this.IMProducts = new HashSet<IMProduct>();
            this.IMProducts1 = new HashSet<IMProduct>();
            this.RawMaterials = new HashSet<RawMaterial>();
            this.TPOProductCEDetails = new HashSet<TPOProductCEDetail>();
            this.TPOProductDimDetails = new HashSet<TPOProductDimDetail>();
            this.TPOProducts = new HashSet<TPOProduct>();
            this.TPOProducts1 = new HashSet<TPOProduct>();
            this.TPOProducts2 = new HashSet<TPOProduct>();
            this.TPOProducts3 = new HashSet<TPOProduct>();
            this.TPOProducts4 = new HashSet<TPOProduct>();
            this.TPOProducts5 = new HashSet<TPOProduct>();
            this.TPOProducts6 = new HashSet<TPOProduct>();
            this.TPOProducts7 = new HashSet<TPOProduct>();
            this.RawMaterialReceiveds = new HashSet<RawMaterialReceived>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<ScrimType> ScrimTypes { get; set; }
        public virtual ICollection<ScrimType> ScrimTypes1 { get; set; }
        public virtual ICollection<ScrimType> ScrimTypes2 { get; set; }
        public virtual UnitOfMeasureType UnitOfMeasureType { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRolls { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRolls1 { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls1 { get; set; }
        public virtual ICollection<IMProd> IMProds { get; set; }
        public virtual ICollection<IMProduct> IMProducts { get; set; }
        public virtual ICollection<IMProduct> IMProducts1 { get; set; }
        public virtual ICollection<RawMaterial> RawMaterials { get; set; }
        public virtual ICollection<TPOProductCEDetail> TPOProductCEDetails { get; set; }
        public virtual ICollection<TPOProductDimDetail> TPOProductDimDetails { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts1 { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts2 { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts3 { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts4 { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts5 { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts6 { get; set; }
        public virtual ICollection<TPOProduct> TPOProducts7 { get; set; }
        public virtual ICollection<RawMaterialReceived> RawMaterialReceiveds { get; set; }
    }
}
