//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.RawMaterialActions = new HashSet<RawMaterialAction>();
            this.ScrimActions = new HashSet<ScrimAction>();
            this.TPOCProductRolls = new HashSet<TPOCProductRoll>();
            this.IMProds = new HashSet<IMProd>();
        }
    
        public int ID { get; set; }
        public int LineID { get; set; }
        public int ProductID { get; set; }
        public int PlantID { get; set; }
        public string Code { get; set; }
        public int RunOrder { get; set; }
        public double RunArea { get; set; }
        public bool Pal { get; set; }
        public bool Complete { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialActions { get; set; }
        public virtual ICollection<ScrimAction> ScrimActions { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual ICollection<IMProd> IMProds { get; set; }
    }
}
