//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPO.Common.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be deleted..
        /// </summary>
        public static string ResponseMessageFailDelete {
            get {
                return ResourceManager.GetString("ResponseMessageFailDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item ID was present..
        /// </summary>
        public static string ResponseMessageFailNoId {
            get {
                return ResourceManager.GetString("ResponseMessageFailNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be found..
        /// </summary>
        public static string ResponseMessageFailNoRecord {
            get {
                return ResourceManager.GetString("ResponseMessageFailNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be saved..
        /// </summary>
        public static string ResponseMessageFailSave {
            get {
                return ResourceManager.GetString("ResponseMessageFailSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This material is associated with a production line or QC tests and cannot be removed..
        /// </summary>
        public static string ResponseMessageMaterialAssociated {
            get {
                return ResourceManager.GetString("ResponseMessageMaterialAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was deleted..
        /// </summary>
        public static string ResponseMessageSuccessDelete {
            get {
                return ResourceManager.GetString("ResponseMessageSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was saved..
        /// </summary>
        public static string ResponseMessageSuccessSave {
            get {
                return ResourceManager.GetString("ResponseMessageSuccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has timed out due to inactivity. You will be redirected to the login page in 5 seconds....
        /// </summary>
        public static string ResponseSessionTimeout {
            get {
                return ResourceManager.GetString("ResponseSessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert-danger.
        /// </summary>
        public static string ResponseTypeError {
            get {
                return ResourceManager.GetString("ResponseTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert-info.
        /// </summary>
        public static string ResponseTypeInfo {
            get {
                return ResourceManager.GetString("ResponseTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert-success.
        /// </summary>
        public static string ResponseTypeSuccess {
            get {
                return ResourceManager.GetString("ResponseTypeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert-warning.
        /// </summary>
        public static string ResponseTypeWarning {
            get {
                return ResourceManager.GetString("ResponseTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. You are not authorized to access the requested resource..
        /// </summary>
        public static string ResponseUnauthorized {
            get {
                return ResourceManager.GetString("ResponseUnauthorized", resourceCulture);
            }
        }
    }
}
