CREATE TABLE [dbo].[ProdLineRollConfig](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LineRollName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ProdLineRollConfig] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


