CREATE TABLE [dbo].[QCKickout]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [LotID] INT NOT NULL, 
    [PlantID] INT NOT NULL, 
    [ProductID] INT NOT NULL, 
    [RollID] INT NOT NULL, 
    [LineID] INT NOT NULL, 
	[ShiftID] INT NOT NULL,
    [QCTechID] INT NULL, 
    [LeadOperatorID] INT NULL, 
    [SupervisorID] INT NULL, 
    [KickoutDate] DATETIME NOT NULL, 
    [RollLengthFT] FLOAT NULL, 
    [RollLengthIN] FLOAT NULL, 
	[RollLengthFTSet] FLOAT NULL,
	[RollLengthINSet] FLOAT NULL,
	[TackLine] FLOAT NULL,
	[LapLine] FLOAT NULL,
	[WeldLine] FLOAT NULL,
	[DateLine] FLOAT NULL,
	[WeldToLapLine] FLOAT NULL,
    [CutStraight] BIT NULL, 
    [SheetFlat] BIT NULL, 
    [GESpec] BIT NULL, 
    [EdgeFlat] BIT NULL, 
    [UnwindStraight] BIT NULL, 
    [CoreWrinkles] BIT NULL, 
    [PrintOK] BIT NULL, 
	[ThickAlarmVerified] BIT NULL,
	[CameraVerified] BIT NULL,
    [Passed] BIT NULL,
	[Comment] NVARCHAR(MAX) NULL,
	[DateEntered] DATETIME NOT NULL,
	[EnteredBy] NVARCHAR(100) NOT NULL,
	[LastModified] DATETIME NOT NULL,
	[ModifiedBy] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_QCKickout_Plant] FOREIGN KEY ([PlantID]) REFERENCES [Plant]([ID]),
	CONSTRAINT [FK_QCKickout_ProductionShift] FOREIGN KEY ([ShiftID]) REFERENCES [ProductionShift]([ID]),
	CONSTRAINT [FK_QCKickout_QCTechID] FOREIGN KEY ([QCTechID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_QCKickout_LeadOperatorID] FOREIGN KEY ([LeadOperatorID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_QCKickout_SupervisorID] FOREIGN KEY ([SupervisorID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_QCKickout_TPOCProductRoll] FOREIGN KEY ([RollID]) REFERENCES [TPOCProductRoll]([ID])
)
