CREATE TABLE [dbo].[QCRedHold]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PlantID] INT NOT NULL, 
    [LineID] INT NOT NULL, 
	[RollID] INT NOT NULL,
	[FailPropertyID] INT NULL,
    [ProductID] INT NOT NULL, 
	[LotID] INT NOT NULL,
	[HoldLotID] INT NULL,
    [QCTechID] INT NULL, 
    [LeadOperatorID] INT NULL, 
    [SupervisorID] INT NULL, 
    [ManagerID] INT NULL, 
    [RedDate] DATE NOT NULL, 
    [Zone] NVARCHAR(50) NULL,
	[RedComments] NVARCHAR(MAX) NULL, 
    [RedCorrectionAction] NVARCHAR(500) NULL, 
    [HoldDate] DATE NULL, 
    [HoldComments] NVARCHAR(MAX) NULL, 
    [ManagerDate] DATE NULL, 
    [ManagerComments] NVARCHAR(MAX) NULL, 
    [PrimeRolls] FLOAT NOT NULL, 
    [PrimeArea] FLOAT NOT NULL, 
    [ReworkRolls] FLOAT NOT NULL, 
    [ReworkArea] FLOAT NOT NULL, 
    [SCRolls] FLOAT NOT NULL, 
    [SCArea] FLOAT NOT NULL,
	[DateEntered] DATETIME NOT NULL,
	[EnteredBy] NVARCHAR(100) NOT NULL,
	[LastModified] DATETIME NOT NULL,
	[ModifiedBy] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_QCRedHold_Plant] FOREIGN KEY ([PlantID]) REFERENCES [Plant](ID), 
    CONSTRAINT [FK_QCRedHold_FailProperty] FOREIGN KEY ([FailPropertyID]) REFERENCES [FailProperty]([ID]),
	CONSTRAINT [FK_QCRedHold_QCTechID] FOREIGN KEY ([QCTechID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_QCRedHold_LeadOperatorID] FOREIGN KEY ([LeadOperatorID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_QCRedHold_SupervisorID] FOREIGN KEY ([SupervisorID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_QCRedHold_ManagerID] FOREIGN KEY ([ManagerID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_QCRedHold_TPOCProductRoll] FOREIGN KEY ([RollID]) REFERENCES [TPOCProductRoll]([ID])
)
