CREATE TABLE [dbo].[RawMaterialQCRedHold]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PlantID] INT NOT NULL, 
    [RawMaterialReceivedID] INT NOT NULL,
	[FailPropertyID] INT NULL,
	[HoldLotID] nvarchar(50) NULL,
    [QCTechID] INT NULL, 
    [LeadOperatorID] INT NULL, 
    [SupervisorID] INT NULL, 
    [ManagerID] INT NULL, 
    [RedDate] DATE NOT NULL, 
    [Zone] NVARCHAR(50) NULL,
	[RedComments] NVARCHAR(MAX) NULL, 
    [RedCorrectionAction] NVARCHAR(500) NULL, 
    [HoldDate] DATE NULL, 
    [HoldComments] NVARCHAR(MAX) NULL, 
    [ManagerDate] DATE NULL, 
    [ManagerComments] NVARCHAR(MAX) NULL, 
	--Next 6 are the QC downgrade matrix fields
    [PrimeBoxCar] FLOAT NOT NULL, 
    [PrimeUOM] FLOAT NOT NULL, 
    [ReworkBoxCar] FLOAT NOT NULL, 
    [ReworkUOM] FLOAT NOT NULL, 
    [ScrapBoxCar] FLOAT NOT NULL, 
    [ScrapUOM] FLOAT NOT NULL,
	[DateEntered] DATETIME NOT NULL,
	[EnteredBy] NVARCHAR(100) NOT NULL,
	[LastModified] DATETIME NOT NULL,
	[ModifiedBy] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_RawMaterialQCRedHold_Plant] FOREIGN KEY ([PlantID]) REFERENCES [Plant](ID), 
    CONSTRAINT [FK_RawMaterialQCRedHold_FailProperty] FOREIGN KEY ([FailPropertyID]) REFERENCES [FailProperty]([ID]),
	CONSTRAINT [FK_RawMaterialQCRedHold_QCTechID] FOREIGN KEY ([QCTechID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_RawMaterialQCRedHold_LeadOperatorID] FOREIGN KEY ([LeadOperatorID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_RawMaterialQCRedHold_SupervisorID] FOREIGN KEY ([SupervisorID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_RawMaterialQCRedHold_ManagerID] FOREIGN KEY ([ManagerID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_RawMaterialQCRedHold_RawMaterialReceived] FOREIGN KEY ([RawMaterialReceivedID]) REFERENCES [RawMaterialReceived]([ID])
)
