CREATE TABLE [dbo].[RawMaterialTest]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PlantID] INT NOT NULL, 
    [UseColorTest] BIT NOT NULL, 
    [ColorLimitTypeID] INT NULL, 
    [ColorLimit1] FLOAT NULL, 
    [ColorLimit2] FLOAT NULL, 
    [UseMFTest] BIT NOT NULL, 
    [MFLimitTypeID] INT NULL, 
    [MFLimit1] FLOAT NOT NULL, 
    [MFLimit2] FLOAT NULL, 
    [UseACTest] BIT NOT NULL, 
    [ACLimitTypeID] INT NULL, 
    [ACLimit1] FLOAT NULL, 
    [ACLimit2] FLOAT NULL, 
    [UseMoistTest] BIT NOT NULL, 
    [MoistLimitTypeID] INT NULL, 
    [MoistLimit1] FLOAT NULL, 
    [MoistLimit2] FLOAT NULL, 
    [UseCBTest] BIT NOT NULL, 
    [CBLimitTypeID] INT NULL, 
    [CBLimit1] FLOAT NULL, 
    [CBLimit2] FLOAT NULL, 
    [UseSpecGrav] BIT NULL, 
    [UseVisual] BIT NULL, 
    [TestFrequency] NVARCHAR(50) NULL, 
    [DateEntered] DATETIME NOT NULL, 
    [EnteredBy] NVARCHAR(100) NOT NULL, 
    [LastModified] DATETIME NOT NULL, 
    [ModifiedBy] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_RawMaterialTest_Plant] FOREIGN KEY ([PlantID]) REFERENCES [Plant]([ID]),
	CONSTRAINT [FK_RawMaterialTest_ColorLimitType] FOREIGN KEY ([ColorLimitTypeID]) REFERENCES [TestLimitType]([ID]),
	CONSTRAINT [FK_RawMaterialTest_MFLimitType] FOREIGN KEY ([MFLimitTypeID]) REFERENCES [TestLimitType]([ID]),
	CONSTRAINT [FK_RawMaterialTest_ACLimitType] FOREIGN KEY ([ACLimitTypeID]) REFERENCES [TestLimitType]([ID]),
	CONSTRAINT [FK_RawMaterialTest_MoistLimitType] FOREIGN KEY ([MoistLimitTypeID]) REFERENCES [TestLimitType]([ID]),
	CONSTRAINT [FK_RawMaterialTest_CBLimitType] FOREIGN KEY ([CBLimitTypeID]) REFERENCES [TestLimitType]([ID])
)
