CREATE TABLE [dbo].[ScrimAction]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PlantID] INT NOT NULL, 
    [LineID] INT NULL, 
    [ShiftID] INT NULL, 
    [WorkOrderID] INT NULL, 
    [RollID] INT NULL, 
	[ScrimRollID] INT NOT NULL,
    [TypeID] INT NOT NULL, 
    [ReasonID] INT NULL, 
    [UserID] INT NOT NULL, 
    [ActionLength] FLOAT NOT NULL, 
    [ActionWeight] FLOAT NOT NULL, 
    [StartLength] FLOAT NOT NULL, 
    [StartWeight] FLOAT NOT NULL, 
    [EndLength] FLOAT NOT NULL, 
    [EndWeight] FLOAT NOT NULL, 
    [ActionDate] DATETIME NOT NULL, 
    [FleeceProd] BIT NULL, 
    [DateEntered] DATETIME NOT NULL, 
    [EnteredBy] NVARCHAR(100) NOT NULL, 
    [LastModified] DATETIME NOT NULL, 
    [ModifiedBy] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_ScrimAction_Plant] FOREIGN KEY ([PlantID]) REFERENCES [Plant]([ID]),
	CONSTRAINT [FK_ScrimAction_WorkOrder] FOREIGN KEY ([WorkOrderID]) REFERENCES [WorkOrder]([ID]),
	CONSTRAINT [FK_ScrimAction_ScrimRoll] FOREIGN KEY ([ScrimRollID]) REFERENCES [ScrimRoll]([ID]),
	CONSTRAINT [FK_ScrimAction_TPOCProductRoll] FOREIGN KEY ([RollID]) REFERENCES [TPOCProductRoll]([ID]),
	CONSTRAINT [FK_ScrimAction_ScrimActionType] FOREIGN KEY ([TypeID]) REFERENCES [ScrimActionType]([ID]),
	CONSTRAINT [FK_ScrimAction_ScrimActionReason] FOREIGN KEY ([ReasonID]) REFERENCES [ScrimActionReason]([ID]),
	CONSTRAINT [FK_ScrimAction_User] FOREIGN KEY ([UserID]) REFERENCES [User]([ID]),
	CONSTRAINT [FK_ScrimAction_ProductionShift] FOREIGN KEY ([ShiftID]) REFERENCES [ProductionShift]([ID])
)
