CREATE TABLE [dbo].[TPOQCColorDetail]
(
	[TPOQCID] INT NOT NULL PRIMARY KEY, 
    [ColorL] FLOAT NULL, 
    [ColorA] FLOAT NULL, 
    [ColorB] FLOAT NULL, 
    [ColorDE] FLOAT NULL, 
    [DateEntered] DATETIME NOT NULL, 
    [EnteredBy] NVARCHAR(100) NOT NULL, 
    [LastModified] DATETIME NOT NULL, 
    [ModifiedBy] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_TPOQCColorDetail_TPOQC] FOREIGN KEY ([TPOQCID]) REFERENCES [TPOQC]([ID])
)
