CREATE TABLE [dbo].[TPOQCThicknessFromEdgeDetail]
(
	[TPOQCID] INT NOT NULL PRIMARY KEY, 
    [EastThick1] FLOAT NULL, 
    [EastThick2] FLOAT NULL, 
    [EastThick3] FLOAT NULL, 
    [EastThick4] FLOAT NULL, 
    [EastThick5] FLOAT NULL, 
    [EastThick6] FLOAT NULL, 
    [EastThick7] FLOAT NULL, 
    [EastThick8] FLOAT NULL, 
    [EastThick9] FLOAT NULL, 
    [EastThick10] FLOAT NULL, 
    [EastThick11] FLOAT NULL, 
    [EastThick12] FLOAT NULL, 
    [WestThick1] FLOAT NULL, 
    [WestThick2] FLOAT NULL, 
    [WestThick3] FLOAT NULL, 
    [WestThick4] FLOAT NULL, 
    [WestThick5] FLOAT NULL, 
    [WestThick6] FLOAT NULL, 
    [WestThick7] FLOAT NULL, 
    [WestThick8] FLOAT NULL, 
    [WestThick9] FLOAT NULL, 
    [WestThick10] FLOAT NULL, 
    [WestThick11] FLOAT NULL, 
    [WestThick12] FLOAT NULL, 
    [DateEntered] DATETIME NOT NULL, 
    [EnteredBy] NVARCHAR(100) NOT NULL, 
    [LastModified] DATETIME NOT NULL, 
    [ModifiedBy] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_TPOQCThicknessFromEdgeDetail_TPOQC] FOREIGN KEY ([TPOQCID]) REFERENCES [TPOQC]([ID])
)
