//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownTimeType
    {
        public DownTimeType()
        {
            this.DownTimeEquipments = new HashSet<DownTimeEquipment>();
            this.DownTimeEquipmentGroups = new HashSet<DownTimeEquipmentGroup>();
            this.DownTimeReasons = new HashSet<DownTimeReason>();
            this.DownTimes = new HashSet<DownTime>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<DownTimeEquipment> DownTimeEquipments { get; set; }
        public virtual ICollection<DownTimeEquipmentGroup> DownTimeEquipmentGroups { get; set; }
        public virtual ICollection<DownTimeReason> DownTimeReasons { get; set; }
        public virtual ICollection<DownTime> DownTimes { get; set; }
    }
}
