//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownTime
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int LineID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int WorkOrderID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public int ShiftID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public System.DateTime DateOccurred { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> DownTimeEquipmentGroupID { get; set; }
        public int DownTimeMinutes { get; set; }
        public System.DateTime ProductionDate { get; set; }
    
        public virtual DownTimeEquipment DownTimeEquipment { get; set; }
        public virtual DownTimeEquipmentGroup DownTimeEquipmentGroup { get; set; }
        public virtual DownTimeReason DownTimeReason { get; set; }
        public virtual DownTimeType DownTimeType { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual ProductionShiftType ProductionShiftType { get; set; }
        public virtual TPOProduct TPOProduct { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
