//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMProd
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int LineID { get; set; }
        public int ShiftID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int WorkOrderID { get; set; }
        public int IMProductID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> IMQCID { get; set; }
        public string Code { get; set; }
        public int PartsCarton { get; set; }
        public double CartonWeight { get; set; }
        public int WeightUoMID { get; set; }
        public Nullable<System.DateTime> AdhesionManufacturesDate { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual IMProduct IMProduct { get; set; }
        public virtual IMQC IMQC { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
