//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMQC
    {
        public IMQC()
        {
            this.IMProds = new HashSet<IMProd>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int ProdLineID { get; set; }
        public int IMProductID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime ProdDate { get; set; }
        public string LabTechnician { get; set; }
        public string Operator { get; set; }
        public Nullable<double> Color { get; set; }
        public string PassFail { get; set; }
        public string Comment { get; set; }
        public int PlantID { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual IMProduct IMProduct { get; set; }
        public virtual ICollection<IMProd> IMProds { get; set; }
    }
}
