//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdLine
    {
        public ProdLine()
        {
            this.IMQCs = new HashSet<IMQC>();
            this.ProdLinesPerformProds = new HashSet<ProdLinesPerformProd>();
            this.TPOFormulationLineProducts = new HashSet<TPOFormulationLineProduct>();
            this.TPOReclaimActions = new HashSet<TPOReclaimAction>();
            this.DownTimeEquipments = new HashSet<DownTimeEquipment>();
            this.DownTimeEquipmentGroups = new HashSet<DownTimeEquipmentGroup>();
            this.DownTimeReasons = new HashSet<DownTimeReason>();
            this.ProdLinesPerforms = new HashSet<ProdLinesPerform>();
            this.RawMaterialActions = new HashSet<RawMaterialAction>();
            this.TPOCurrentScrims = new HashSet<TPOCurrentScrim>();
            this.ProductionShiftUses = new HashSet<ProductionShiftUse>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.ProdDateChanges = new HashSet<ProdDateChange>();
            this.ProdComments = new HashSet<ProdComment>();
            this.TPOCProductRolls = new HashSet<TPOCProductRoll>();
            this.DownTimes = new HashSet<DownTime>();
            this.WorkOrderShiftDatas = new HashSet<WorkOrderShiftData>();
            this.WorkOrderShiftDataFormulations = new HashSet<WorkOrderShiftDataFormulation>();
            this.TPOBatches = new HashSet<TPOBatch>();
            this.TPOCurrentRawMaterials = new HashSet<TPOCurrentRawMaterial>();
            this.SupervisorOnShifts = new HashSet<SupervisorOnShift>();
            this.TPOLineScraps = new HashSet<TPOLineScrap>();
            this.TPOReworkRolls = new HashSet<TPOReworkRoll>();
            this.IMProds = new HashSet<IMProd>();
        }
    
        public int ID { get; set; }
        public string LineDescCode { get; set; }
        public string LineDesc { get; set; }
        public int LineTypeID { get; set; }
        public int LabelID { get; set; }
        public string TPOMorC { get; set; }
        public int RepOrder { get; set; }
        public string RCComp { get; set; }
        public int PlantID { get; set; }
        public int LineRollConfigID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CurrentWorkOrderID { get; set; }
    
        public virtual ICollection<IMQC> IMQCs { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ProdLineRollConfig ProdLineRollConfig { get; set; }
        public virtual ProdLineType ProdLineType { get; set; }
        public virtual ICollection<ProdLinesPerformProd> ProdLinesPerformProds { get; set; }
        public virtual ICollection<TPOFormulationLineProduct> TPOFormulationLineProducts { get; set; }
        public virtual ICollection<TPOReclaimAction> TPOReclaimActions { get; set; }
        public virtual ICollection<DownTimeEquipment> DownTimeEquipments { get; set; }
        public virtual ICollection<DownTimeEquipmentGroup> DownTimeEquipmentGroups { get; set; }
        public virtual ICollection<DownTimeReason> DownTimeReasons { get; set; }
        public virtual ICollection<ProdLinesPerform> ProdLinesPerforms { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialActions { get; set; }
        public virtual ICollection<TPOCurrentScrim> TPOCurrentScrims { get; set; }
        public virtual ICollection<ProductionShiftUse> ProductionShiftUses { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual ICollection<ProdDateChange> ProdDateChanges { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<ProdComment> ProdComments { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual ICollection<DownTime> DownTimes { get; set; }
        public virtual ICollection<WorkOrderShiftData> WorkOrderShiftDatas { get; set; }
        public virtual ICollection<WorkOrderShiftDataFormulation> WorkOrderShiftDataFormulations { get; set; }
        public virtual ICollection<TPOBatch> TPOBatches { get; set; }
        public virtual ICollection<TPOCurrentRawMaterial> TPOCurrentRawMaterials { get; set; }
        public virtual ICollection<SupervisorOnShift> SupervisorOnShifts { get; set; }
        public virtual ICollection<TPOLineScrap> TPOLineScraps { get; set; }
        public virtual ICollection<TPOReworkRoll> TPOReworkRolls { get; set; }
        public virtual ICollection<IMProd> IMProds { get; set; }
    }
}
