//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdLinesPerform
    {
        public int ID { get; set; }
        public int LocID { get; set; }
        public string LineCode { get; set; }
        public double Uptime { get; set; }
        public double Yield { get; set; }
        public double Throughput { get; set; }
        public double OEE { get; set; }
        public string TPTUse { get; set; }
        public double SchedFactor { get; set; }
        public int ProdLineID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ThroughputUoMID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
