//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdLineRollConfig
    {
        public ProdLineRollConfig()
        {
            this.ProdLines = new HashSet<ProdLine>();
        }
    
        public int ID { get; set; }
        public string RollName { get; set; }
        public int TypeID { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<ProdLine> ProdLines { get; set; }
        public virtual ProdLineType ProdLineType { get; set; }
    }
}
