//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCKickout
    {
        public int ID { get; set; }
        public int LotID { get; set; }
        public int PlantID { get; set; }
        public int ProductID { get; set; }
        public int RollID { get; set; }
        public int LineID { get; set; }
        public int ShiftID { get; set; }
        public Nullable<int> QCTechID { get; set; }
        public Nullable<int> LeadOperatorID { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public System.DateTime KickoutDate { get; set; }
        public Nullable<double> RollLengthFT { get; set; }
        public Nullable<double> RollLengthIN { get; set; }
        public Nullable<double> RollLengthFTSet { get; set; }
        public Nullable<double> RollLengthINSet { get; set; }
        public Nullable<double> TackLine { get; set; }
        public Nullable<double> LapLine { get; set; }
        public Nullable<double> WeldLine { get; set; }
        public Nullable<double> DateLine { get; set; }
        public Nullable<double> WeldToLapLine { get; set; }
        public Nullable<bool> CutStraight { get; set; }
        public Nullable<bool> SheetFlat { get; set; }
        public Nullable<bool> GESpec { get; set; }
        public Nullable<bool> EdgeFlat { get; set; }
        public Nullable<bool> UnwindStraight { get; set; }
        public Nullable<bool> CoreWrinkles { get; set; }
        public Nullable<bool> PrintOK { get; set; }
        public Nullable<bool> ThickAlarmVerified { get; set; }
        public Nullable<bool> CameraVerified { get; set; }
        public Nullable<bool> Passed { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual TPOCProductRoll TPOCProductRoll { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
