//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialReceivedSizeLimit
    {
        public RawMaterialReceivedSizeLimit()
        {
            this.RawMaterialReceiveds = new HashSet<RawMaterialReceived>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public string Code { get; set; }
        public bool View { get; set; }
        public double LowLimit { get; set; }
        public double HighLimit { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<RawMaterialReceived> RawMaterialReceiveds { get; set; }
    }
}
