//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialQC
    {
        public RawMaterialQC()
        {
            this.RawMaterialQCRedHolds = new HashSet<RawMaterialQCRedHold>();
            this.RawMaterialSpecificGravities = new HashSet<RawMaterialSpecificGravity>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public Nullable<int> QCTechUserID { get; set; }
        public Nullable<double> SpecGrav { get; set; }
        public Nullable<double> ColorCoA { get; set; }
        public Nullable<double> ColorFS { get; set; }
        public Nullable<double> MFCoA { get; set; }
        public Nullable<double> MFFS { get; set; }
        public Nullable<double> ACCoA { get; set; }
        public Nullable<double> ACFS { get; set; }
        public Nullable<double> MoistCoA { get; set; }
        public Nullable<double> MoistFS { get; set; }
        public Nullable<double> CBCoA { get; set; }
        public Nullable<double> CBFS { get; set; }
        public string BoxCarTested { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public int RawMaterialReceivedID { get; set; }
        public int QCVisualInspectionID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual QCVisualInspectionType QCVisualInspectionType { get; set; }
        public virtual User User { get; set; }
        public virtual RawMaterialReceived RawMaterialReceived { get; set; }
        public virtual ICollection<RawMaterialQCRedHold> RawMaterialQCRedHolds { get; set; }
        public virtual ICollection<RawMaterialSpecificGravity> RawMaterialSpecificGravities { get; set; }
    }
}
