//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialTest
    {
        public int ID { get; set; }
        public int PlantID { get; set; }
        public bool UseColorTest { get; set; }
        public Nullable<int> ColorLimitTypeID { get; set; }
        public Nullable<double> ColorLimit1 { get; set; }
        public Nullable<double> ColorLimit2 { get; set; }
        public bool UseMFTest { get; set; }
        public Nullable<int> MFLimitTypeID { get; set; }
        public Nullable<double> MFLimit1 { get; set; }
        public Nullable<double> MFLimit2 { get; set; }
        public bool UseACTest { get; set; }
        public Nullable<int> ACLimitTypeID { get; set; }
        public Nullable<double> ACLimit1 { get; set; }
        public Nullable<double> ACLimit2 { get; set; }
        public bool UseMoistTest { get; set; }
        public Nullable<int> MoistLimitTypeID { get; set; }
        public Nullable<double> MoistLimit1 { get; set; }
        public Nullable<double> MoistLimit2 { get; set; }
        public bool UseCBTest { get; set; }
        public Nullable<int> CBLimitTypeID { get; set; }
        public Nullable<double> CBLimit1 { get; set; }
        public Nullable<double> CBLimit2 { get; set; }
        public Nullable<bool> UseSpecGrav { get; set; }
        public Nullable<bool> UseVisual { get; set; }
        public string TestFrequency { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public int RawMaterialID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual TestLimitType TestLimitType { get; set; }
        public virtual TestLimitType TestLimitType1 { get; set; }
        public virtual TestLimitType TestLimitType2 { get; set; }
        public virtual TestLimitType TestLimitType3 { get; set; }
        public virtual TestLimitType TestLimitType4 { get; set; }
    }
}
