//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrimType
    {
        public ScrimType()
        {
            this.ScrimRolls = new HashSet<ScrimRoll>();
            this.TPOCurrentScrims = new HashSet<TPOCurrentScrim>();
            this.TPOCurrentScrims1 = new HashSet<TPOCurrentScrim>();
            this.TPOCurrentScrims2 = new HashSet<TPOCurrentScrim>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int WidthUoMID { get; set; }
        public int WeightUoMID { get; set; }
        public int LengthUoMID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
        public double Weight { get; set; }
        public bool IsLiner { get; set; }
        public System.DateTime LastModified { get; set; }
        public int AreaUoMID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<ScrimRoll> ScrimRolls { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure2 { get; set; }
        public virtual ICollection<TPOCurrentScrim> TPOCurrentScrims { get; set; }
        public virtual ICollection<TPOCurrentScrim> TPOCurrentScrims1 { get; set; }
        public virtual ICollection<TPOCurrentScrim> TPOCurrentScrims2 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure3 { get; set; }
    }
}
