//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOLineScrapCode
    {
        public TPOLineScrapCode()
        {
            this.TPOLineScraps = new HashSet<TPOLineScrap>();
        }
    
        public int ID { get; set; }
        public int GroupID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool View { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual TPOLineScrapCodeGroup TPOLineScrapCodeGroup { get; set; }
        public virtual ICollection<TPOLineScrap> TPOLineScraps { get; set; }
    }
}
