//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOLineScrap
    {
        public TPOLineScrap()
        {
            this.TPOReworkActions = new HashSet<TPOReworkAction>();
        }
    
        public int ID { get; set; }
        public int PlantID { get; set; }
        public int ShiftID { get; set; }
        public int WorkOrderID { get; set; }
        public Nullable<int> ReworkRollID { get; set; }
        public int TypeID { get; set; }
        public string Code { get; set; }
        public string ScrapCode { get; set; }
        public int BatchNumber { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Weight { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public int WeightUoMID { get; set; }
        public int WidthUoMID { get; set; }
        public int LineScrapCodeGroupID { get; set; }
        public int LineScrapCodeID { get; set; }
        public int LengthUoMID { get; set; }
        public int ProdLinesID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual TPOLineScrapType TPOLineScrapType { get; set; }
        public virtual TPOReworkRoll TPOReworkRoll { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure2 { get; set; }
        public virtual TPOLineScrapCode TPOLineScrapCode { get; set; }
        public virtual TPOLineScrapCodeGroup TPOLineScrapCodeGroup { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkActions { get; set; }
    }
}
