//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOProduct
    {
        public TPOProduct()
        {
            this.ProdLinesPerformProds = new HashSet<ProdLinesPerformProd>();
            this.TPOFormulationLineProducts = new HashSet<TPOFormulationLineProduct>();
            this.TPOProductStandardCosts = new HashSet<TPOProductStandardCost>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.TPOCProductRolls = new HashSet<TPOCProductRoll>();
            this.DownTimes = new HashSet<DownTime>();
            this.TPOReworkRolls = new HashSet<TPOReworkRoll>();
        }
    
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public string ProductDesc { get; set; }
        public double Thick { get; set; }
        public int ThickUnit { get; set; }
        public double Width { get; set; }
        public double MasRollLength { get; set; }
        public double ContRollLength { get; set; }
        public int LengthWidthUnit { get; set; }
        public int AreaUnit { get; set; }
        public int WeightUnit { get; set; }
        public int ScrimTypeID { get; set; }
        public int QtyMade { get; set; }
        public double WtperArea { get; set; }
        public int ProductLabelID { get; set; }
        public int FormNo { get; set; }
        public int RollsPerLot { get; set; }
        public int ThickTestUoM { get; set; }
        public int WidthTestUoM { get; set; }
        public int ForceTestUoM { get; set; }
        public Nullable<double> ThickMin { get; set; }
        public Nullable<double> ThickMax { get; set; }
        public Nullable<double> WidthMin { get; set; }
        public Nullable<double> WidthMax { get; set; }
        public Nullable<double> GEWidthMin { get; set; }
        public Nullable<double> GEWidthMax { get; set; }
        public Nullable<double> GEThicknessMin { get; set; }
        public Nullable<double> PlyAdhMin { get; set; }
        public Nullable<double> PlyAdhAvg { get; set; }
        public int ProductCapCoreID { get; set; }
        public int ProductGrabID { get; set; }
        public Nullable<double> DimStab { get; set; }
        public bool UseSecThick { get; set; }
        public int ThickTestUoM2 { get; set; }
        public Nullable<double> WeldTestMin { get; set; }
        public Nullable<double> WeldTestMax { get; set; }
        public int ProductCEID { get; set; }
        public Nullable<double> PunctMinTD { get; set; }
        public int PunctUoM { get; set; }
        public Nullable<double> ThickAvgMin { get; set; }
        public Nullable<double> ThickAvgMax { get; set; }
        public int RollsPerLotPal { get; set; }
        public bool IsREPEL { get; set; }
        public Nullable<double> ThickAvg { get; set; }
        public int ProductDimID { get; set; }
        public bool Active { get; set; }
        public int PlantID { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<ProdLinesPerformProd> ProdLinesPerformProds { get; set; }
        public virtual ICollection<TPOFormulationLineProduct> TPOFormulationLineProducts { get; set; }
        public virtual TPOProductCapCoreDetail TPOProductCapCoreDetail { get; set; }
        public virtual TPOProductCEDetail TPOProductCEDetail { get; set; }
        public virtual TPOProductDimDetail TPOProductDimDetail { get; set; }
        public virtual TPOProductGrabDetail TPOProductGrabDetail { get; set; }
        public virtual TPOProductLabelDetail TPOProductLabelDetail { get; set; }
        public virtual UnitOfMeasure ThickUnitOfMeasure { get; set; }
        public virtual UnitOfMeasure LengthWidthUnitOfMeasure { get; set; }
        public virtual UnitOfMeasure AreUnitOfMeasure { get; set; }
        public virtual UnitOfMeasure ThickTestUnitOfMeasure { get; set; }
        public virtual UnitOfMeasure WidthTestUnitOfMeasure { get; set; }
        public virtual UnitOfMeasure ForceTestUnitOfMeasure { get; set; }
        public virtual UnitOfMeasure ThickTestUnitOfMeasure2 { get; set; }
        public virtual UnitOfMeasure PunctUnitOfMeasure { get; set; }
        public virtual ICollection<TPOProductStandardCost> TPOProductStandardCosts { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual ICollection<DownTime> DownTimes { get; set; }
        public virtual ICollection<TPOReworkRoll> TPOReworkRolls { get; set; }
    }
}
