//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOProductLabelDetail
    {
        public TPOProductLabelDetail()
        {
            this.TPOProducts = new HashSet<TPOProduct>();
        }
    
        public int ID { get; set; }
        public string Label1 { get; set; }
        public string Label2 { get; set; }
        public string Label3 { get; set; }
    
        public virtual ICollection<TPOProduct> TPOProducts { get; set; }
    }
}
