//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOProductCapCoreDetail
    {
        public TPOProductCapCoreDetail()
        {
            this.TPOProducts = new HashSet<TPOProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<double> CapThickMin { get; set; }
        public Nullable<double> CapThickAvg { get; set; }
        public Nullable<double> CapThickMax { get; set; }
        public Nullable<double> CoreThickMin { get; set; }
        public Nullable<double> CoreThickAvg { get; set; }
        public Nullable<double> CoreThickMax { get; set; }
        public Nullable<double> CapAshMin { get; set; }
        public Nullable<double> CapAshMax { get; set; }
        public Nullable<double> CoreAshMin { get; set; }
        public Nullable<double> CoreAshMax { get; set; }
    
        public virtual ICollection<TPOProduct> TPOProducts { get; set; }
    }
}
