//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOProductGrabDetail
    {
        public TPOProductGrabDetail()
        {
            this.TPOProducts = new HashSet<TPOProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<double> GrabTensMinMD { get; set; }
        public Nullable<double> GrabElongMinMD { get; set; }
        public Nullable<double> GrabTearMin { get; set; }
        public Nullable<double> GrabTensMinTD { get; set; }
        public Nullable<double> GrabElongMinTD { get; set; }
        public Nullable<double> GrabTearMinTD { get; set; }
    
        public virtual ICollection<TPOProduct> TPOProducts { get; set; }
    }
}
