//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOReworkRoll
    {
        public TPOReworkRoll()
        {
            this.TPOLineScraps = new HashSet<TPOLineScrap>();
            this.TPOReworkActions = new HashSet<TPOReworkAction>();
            this.TPOReworkActions1 = new HashSet<TPOReworkAction>();
        }
    
        public int ID { get; set; }
        public int LineID { get; set; }
        public int ShiftID { get; set; }
        public int PlantID { get; set; }
        public string Code { get; set; }
        public double Length { get; set; }
        public int LengthUoMID { get; set; }
        public double Weight { get; set; }
        public int WeightUoMID { get; set; }
        public bool Processed { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public int TPOProductID { get; set; }
        public double Width { get; set; }
        public int WidthUoMID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
        public virtual ICollection<TPOLineScrap> TPOLineScraps { get; set; }
        public virtual UnitOfMeasure LengthUnitOfMeasure { get; set; }
        public virtual UnitOfMeasure WeightUnitOfMeasure { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual TPOProduct TPOProduct { get; set; }
        public virtual UnitOfMeasure WidthUnitOfMeasure { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkActions { get; set; }
        public virtual ICollection<TPOReworkAction> TPOReworkActions1 { get; set; }
    }
}
