//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasureType
    {
        public UnitOfMeasureType()
        {
            this.UnitOfMeasures = new HashSet<UnitOfMeasure>();
            this.UnitOfMeasureDefaults = new HashSet<UnitOfMeasureDefault>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string Enteredby { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual ICollection<UnitOfMeasureDefault> UnitOfMeasureDefaults { get; set; }
    }
}
