//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.ScrimActions = new HashSet<ScrimAction>();
            this.TPOCProductRolls = new HashSet<TPOCProductRoll>();
            this.RawMaterialActions = new HashSet<RawMaterialAction>();
            this.TPOLineScraps = new HashSet<TPOLineScrap>();
            this.ProdLines = new HashSet<ProdLine>();
            this.ProdComments = new HashSet<ProdComment>();
            this.DownTimes = new HashSet<DownTime>();
            this.WorkOrderShiftDatas = new HashSet<WorkOrderShiftData>();
            this.WorkOrderShiftDataFormulations = new HashSet<WorkOrderShiftDataFormulation>();
            this.IMProds = new HashSet<IMProd>();
        }
    
        public int ID { get; set; }
        public int LineID { get; set; }
        public int PlantID { get; set; }
        public string Code { get; set; }
        public int RunOrder { get; set; }
        public double RunArea { get; set; }
        public bool Pal { get; set; }
        public bool Complete { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> TPOProductID { get; set; }
        public Nullable<int> IMProductID { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ICollection<ScrimAction> ScrimActions { get; set; }
        public virtual ICollection<TPOCProductRoll> TPOCProductRolls { get; set; }
        public virtual ICollection<RawMaterialAction> RawMaterialActions { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual IMProduct IMProduct { get; set; }
        public virtual TPOProduct TPOProduct { get; set; }
        public virtual ICollection<TPOLineScrap> TPOLineScraps { get; set; }
        public virtual ICollection<ProdLine> ProdLines { get; set; }
        public virtual ICollection<ProdComment> ProdComments { get; set; }
        public virtual ICollection<DownTime> DownTimes { get; set; }
        public virtual ICollection<WorkOrderShiftData> WorkOrderShiftDatas { get; set; }
        public virtual ICollection<WorkOrderShiftDataFormulation> WorkOrderShiftDataFormulations { get; set; }
        public virtual ICollection<IMProd> IMProds { get; set; }
    }
}
