//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderShiftData
    {
        public int ID { get; set; }
        public int LineID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public double ScrimAreaUsed { get; set; }
        public double ScrimWeightUsed { get; set; }
        public double DrainedResin { get; set; }
        public int PlantID { get; set; }
        public string EnteredBy { get; set; }
        public string ModifiedBy { get; set; }
        public int ShiftID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual ProdLine ProdLine { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ProductionShift ProductionShift { get; set; }
    }
}
